package main.java.generator.po;

public class Argue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column argue.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column argue.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column argue.litigant
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String litigant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column argue.argument
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String argument;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column argue.id
     *
     * @return the value of argue.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column argue.id
     *
     * @param id the value for argue.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column argue.ajxh
     *
     * @return the value of argue.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column argue.ajxh
     *
     * @param ajxh the value for argue.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column argue.litigant
     *
     * @return the value of argue.litigant
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getLitigant() {
        return litigant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column argue.litigant
     *
     * @param litigant the value for argue.litigant
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setLitigant(String litigant) {
        this.litigant = litigant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column argue.argument
     *
     * @return the value of argue.argument
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getArgument() {
        return argument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column argue.argument
     *
     * @param argument the value for argue.argument
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setArgument(String argument) {
        this.argument = argument;
    }
}