package main.java.generator.po;

public class Court {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court.JBFY
     *
     * @mbg.generated Thu Apr 27 18:47:26 CST 2017
     */
    private String jbfy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court.JBFY
     *
     * @return the value of court.JBFY
     *
     * @mbg.generated Thu Apr 27 18:47:26 CST 2017
     */
    public String getJbfy() {
        return jbfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court.JBFY
     *
     * @param jbfy the value for court.JBFY
     *
     * @mbg.generated Thu Apr 27 18:47:26 CST 2017
     */
    public void setJbfy(String jbfy) {
        this.jbfy = jbfy;
    }
}