package main.java.generator.po;

import java.util.Date;

public class Edit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edit.ajxh
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edit.userId
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edit.lastEditTime
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    private Date lastedittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edit.ajxh
     *
     * @return the value of edit.ajxh
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edit.ajxh
     *
     * @param ajxh the value for edit.ajxh
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edit.userId
     *
     * @return the value of edit.userId
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edit.userId
     *
     * @param userid the value for edit.userId
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edit.lastEditTime
     *
     * @return the value of edit.lastEditTime
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    public Date getLastedittime() {
        return lastedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edit.lastEditTime
     *
     * @param lastedittime the value for edit.lastEditTime
     *
     * @mbg.generated Thu Apr 27 21:00:19 CST 2017
     */
    public void setLastedittime(Date lastedittime) {
        this.lastedittime = lastedittime;
    }
}