package main.java.generator.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EditExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public EditExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAjxhIsNull() {
			addCriterion("ajxh is null");
			return (Criteria) this;
		}

		public Criteria andAjxhIsNotNull() {
			addCriterion("ajxh is not null");
			return (Criteria) this;
		}

		public Criteria andAjxhEqualTo(Integer value) {
			addCriterion("ajxh =", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhNotEqualTo(Integer value) {
			addCriterion("ajxh <>", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhGreaterThan(Integer value) {
			addCriterion("ajxh >", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhGreaterThanOrEqualTo(Integer value) {
			addCriterion("ajxh >=", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhLessThan(Integer value) {
			addCriterion("ajxh <", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhLessThanOrEqualTo(Integer value) {
			addCriterion("ajxh <=", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhIn(List<Integer> values) {
			addCriterion("ajxh in", values, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhNotIn(List<Integer> values) {
			addCriterion("ajxh not in", values, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhBetween(Integer value1, Integer value2) {
			addCriterion("ajxh between", value1, value2, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhNotBetween(Integer value1, Integer value2) {
			addCriterion("ajxh not between", value1, value2, "ajxh");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andLastedittimeIsNull() {
			addCriterion("lastEditTime is null");
			return (Criteria) this;
		}

		public Criteria andLastedittimeIsNotNull() {
			addCriterion("lastEditTime is not null");
			return (Criteria) this;
		}

		public Criteria andLastedittimeEqualTo(Date value) {
			addCriterion("lastEditTime =", value, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeNotEqualTo(Date value) {
			addCriterion("lastEditTime <>", value, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeGreaterThan(Date value) {
			addCriterion("lastEditTime >", value, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lastEditTime >=", value, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeLessThan(Date value) {
			addCriterion("lastEditTime <", value, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeLessThanOrEqualTo(Date value) {
			addCriterion("lastEditTime <=", value, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeIn(List<Date> values) {
			addCriterion("lastEditTime in", values, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeNotIn(List<Date> values) {
			addCriterion("lastEditTime not in", values, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeBetween(Date value1, Date value2) {
			addCriterion("lastEditTime between", value1, value2, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andLastedittimeNotBetween(Date value1, Date value2) {
			addCriterion("lastEditTime not between", value1, value2, "lastedittime");
			return (Criteria) this;
		}

		public Criteria andCreatatIsNull() {
			addCriterion("creatAt is null");
			return (Criteria) this;
		}

		public Criteria andCreatatIsNotNull() {
			addCriterion("creatAt is not null");
			return (Criteria) this;
		}

		public Criteria andCreatatEqualTo(Date value) {
			addCriterion("creatAt =", value, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatNotEqualTo(Date value) {
			addCriterion("creatAt <>", value, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatGreaterThan(Date value) {
			addCriterion("creatAt >", value, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatGreaterThanOrEqualTo(Date value) {
			addCriterion("creatAt >=", value, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatLessThan(Date value) {
			addCriterion("creatAt <", value, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatLessThanOrEqualTo(Date value) {
			addCriterion("creatAt <=", value, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatIn(List<Date> values) {
			addCriterion("creatAt in", values, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatNotIn(List<Date> values) {
			addCriterion("creatAt not in", values, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatBetween(Date value1, Date value2) {
			addCriterion("creatAt between", value1, value2, "creatat");
			return (Criteria) this;
		}

		public Criteria andCreatatNotBetween(Date value1, Date value2) {
			addCriterion("creatAt not between", value1, value2, "creatat");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edit
	 * @mbg.generated  Sat May 13 15:52:25 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edit
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 27 21:00:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}