package main.java.generator.po;

public class Evidence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.name
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.number
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.type
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.unit
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.submitterId
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer submitterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.detail
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.id
     *
     * @return the value of evidence.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.id
     *
     * @param id the value for evidence.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.name
     *
     * @return the value of evidence.name
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.name
     *
     * @param name the value for evidence.name
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.number
     *
     * @return the value of evidence.number
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.number
     *
     * @param number the value for evidence.number
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.type
     *
     * @return the value of evidence.type
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.type
     *
     * @param type the value for evidence.type
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.unit
     *
     * @return the value of evidence.unit
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.unit
     *
     * @param unit the value for evidence.unit
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.submitterId
     *
     * @return the value of evidence.submitterId
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getSubmitterid() {
        return submitterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.submitterId
     *
     * @param submitterid the value for evidence.submitterId
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setSubmitterid(Integer submitterid) {
        this.submitterid = submitterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.ajxh
     *
     * @return the value of evidence.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.ajxh
     *
     * @param ajxh the value for evidence.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.detail
     *
     * @return the value of evidence.detail
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.detail
     *
     * @param detail the value for evidence.detail
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }
}