package main.java.generator.po;

public class EvSubmmitter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evsubmmitter.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evsubmmitter.submitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String submitter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evsubmmitter.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer ajxh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evsubmmitter.id
     *
     * @return the value of evsubmmitter.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evsubmmitter.id
     *
     * @param id the value for evsubmmitter.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evsubmmitter.submitter
     *
     * @return the value of evsubmmitter.submitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getSubmitter() {
        return submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evsubmmitter.submitter
     *
     * @param submitter the value for evsubmmitter.submitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setSubmitter(String submitter) {
        this.submitter = submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evsubmmitter.ajxh
     *
     * @return the value of evsubmmitter.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evsubmmitter.ajxh
     *
     * @param ajxh the value for evsubmmitter.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }
}