package main.java.generator.po;

import java.util.ArrayList;
import java.util.List;

public class ExamSubmmitterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public ExamSubmmitterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAjxhIsNull() {
            addCriterion("ajxh is null");
            return (Criteria) this;
        }

        public Criteria andAjxhIsNotNull() {
            addCriterion("ajxh is not null");
            return (Criteria) this;
        }

        public Criteria andAjxhEqualTo(Integer value) {
            addCriterion("ajxh =", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhNotEqualTo(Integer value) {
            addCriterion("ajxh <>", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhGreaterThan(Integer value) {
            addCriterion("ajxh >", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhGreaterThanOrEqualTo(Integer value) {
            addCriterion("ajxh >=", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhLessThan(Integer value) {
            addCriterion("ajxh <", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhLessThanOrEqualTo(Integer value) {
            addCriterion("ajxh <=", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhIn(List<Integer> values) {
            addCriterion("ajxh in", values, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhNotIn(List<Integer> values) {
            addCriterion("ajxh not in", values, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhBetween(Integer value1, Integer value2) {
            addCriterion("ajxh between", value1, value2, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhNotBetween(Integer value1, Integer value2) {
            addCriterion("ajxh not between", value1, value2, "ajxh");
            return (Criteria) this;
        }

        public Criteria andSubmitter1IsNull() {
            addCriterion("submitter1 is null");
            return (Criteria) this;
        }

        public Criteria andSubmitter1IsNotNull() {
            addCriterion("submitter1 is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitter1EqualTo(String value) {
            addCriterion("submitter1 =", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1NotEqualTo(String value) {
            addCriterion("submitter1 <>", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1GreaterThan(String value) {
            addCriterion("submitter1 >", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1GreaterThanOrEqualTo(String value) {
            addCriterion("submitter1 >=", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1LessThan(String value) {
            addCriterion("submitter1 <", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1LessThanOrEqualTo(String value) {
            addCriterion("submitter1 <=", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1Like(String value) {
            addCriterion("submitter1 like", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1NotLike(String value) {
            addCriterion("submitter1 not like", value, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1In(List<String> values) {
            addCriterion("submitter1 in", values, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1NotIn(List<String> values) {
            addCriterion("submitter1 not in", values, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1Between(String value1, String value2) {
            addCriterion("submitter1 between", value1, value2, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter1NotBetween(String value1, String value2) {
            addCriterion("submitter1 not between", value1, value2, "submitter1");
            return (Criteria) this;
        }

        public Criteria andSubmitter2IsNull() {
            addCriterion("submitter2 is null");
            return (Criteria) this;
        }

        public Criteria andSubmitter2IsNotNull() {
            addCriterion("submitter2 is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitter2EqualTo(String value) {
            addCriterion("submitter2 =", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2NotEqualTo(String value) {
            addCriterion("submitter2 <>", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2GreaterThan(String value) {
            addCriterion("submitter2 >", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2GreaterThanOrEqualTo(String value) {
            addCriterion("submitter2 >=", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2LessThan(String value) {
            addCriterion("submitter2 <", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2LessThanOrEqualTo(String value) {
            addCriterion("submitter2 <=", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2Like(String value) {
            addCriterion("submitter2 like", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2NotLike(String value) {
            addCriterion("submitter2 not like", value, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2In(List<String> values) {
            addCriterion("submitter2 in", values, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2NotIn(List<String> values) {
            addCriterion("submitter2 not in", values, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2Between(String value1, String value2) {
            addCriterion("submitter2 between", value1, value2, "submitter2");
            return (Criteria) this;
        }

        public Criteria andSubmitter2NotBetween(String value1, String value2) {
            addCriterion("submitter2 not between", value1, value2, "submitter2");
            return (Criteria) this;
        }

        public Criteria andConfirmedallIsNull() {
            addCriterion("confirmedAll is null");
            return (Criteria) this;
        }

        public Criteria andConfirmedallIsNotNull() {
            addCriterion("confirmedAll is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmedallEqualTo(Boolean value) {
            addCriterion("confirmedAll =", value, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallNotEqualTo(Boolean value) {
            addCriterion("confirmedAll <>", value, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallGreaterThan(Boolean value) {
            addCriterion("confirmedAll >", value, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallGreaterThanOrEqualTo(Boolean value) {
            addCriterion("confirmedAll >=", value, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallLessThan(Boolean value) {
            addCriterion("confirmedAll <", value, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallLessThanOrEqualTo(Boolean value) {
            addCriterion("confirmedAll <=", value, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallIn(List<Boolean> values) {
            addCriterion("confirmedAll in", values, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallNotIn(List<Boolean> values) {
            addCriterion("confirmedAll not in", values, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallBetween(Boolean value1, Boolean value2) {
            addCriterion("confirmedAll between", value1, value2, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andConfirmedallNotBetween(Boolean value1, Boolean value2) {
            addCriterion("confirmedAll not between", value1, value2, "confirmedall");
            return (Criteria) this;
        }

        public Criteria andHaschildIsNull() {
            addCriterion("hasChild is null");
            return (Criteria) this;
        }

        public Criteria andHaschildIsNotNull() {
            addCriterion("hasChild is not null");
            return (Criteria) this;
        }

        public Criteria andHaschildEqualTo(Boolean value) {
            addCriterion("hasChild =", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildNotEqualTo(Boolean value) {
            addCriterion("hasChild <>", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildGreaterThan(Boolean value) {
            addCriterion("hasChild >", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildGreaterThanOrEqualTo(Boolean value) {
            addCriterion("hasChild >=", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildLessThan(Boolean value) {
            addCriterion("hasChild <", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildLessThanOrEqualTo(Boolean value) {
            addCriterion("hasChild <=", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildIn(List<Boolean> values) {
            addCriterion("hasChild in", values, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildNotIn(List<Boolean> values) {
            addCriterion("hasChild not in", values, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildBetween(Boolean value1, Boolean value2) {
            addCriterion("hasChild between", value1, value2, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildNotBetween(Boolean value1, Boolean value2) {
            addCriterion("hasChild not between", value1, value2, "haschild");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table examsubmmitter
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 27 15:03:15 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}