package main.java.generator.po;

public class ExamEv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examev.id
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examev.ajxh
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examev.evidence
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    private String evidence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examev.confirmed
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    private Boolean confirmed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examev.comment
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examev.submitterId
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    private Integer submitterid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examev.id
     *
     * @return the value of examev.id
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examev.id
     *
     * @param id the value for examev.id
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examev.ajxh
     *
     * @return the value of examev.ajxh
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examev.ajxh
     *
     * @param ajxh the value for examev.ajxh
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examev.evidence
     *
     * @return the value of examev.evidence
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public String getEvidence() {
        return evidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examev.evidence
     *
     * @param evidence the value for examev.evidence
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public void setEvidence(String evidence) {
        this.evidence = evidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examev.confirmed
     *
     * @return the value of examev.confirmed
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public Boolean getConfirmed() {
        return confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examev.confirmed
     *
     * @param confirmed the value for examev.confirmed
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examev.comment
     *
     * @return the value of examev.comment
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examev.comment
     *
     * @param comment the value for examev.comment
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examev.submitterId
     *
     * @return the value of examev.submitterId
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public Integer getSubmitterid() {
        return submitterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examev.submitterId
     *
     * @param submitterid the value for examev.submitterId
     *
     * @mbg.generated Thu Apr 27 16:01:38 CST 2017
     */
    public void setSubmitterid(Integer submitterid) {
        this.submitterid = submitterid;
    }
}