package main.java.generator.po;

public class ExamSubmmitter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examsubmmitter.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examsubmmitter.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examsubmmitter.submitter1
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String submitter1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examsubmmitter.submitter2
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String submitter2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examsubmmitter.confirmedAll
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Boolean confirmedall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examsubmmitter.hasChild
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Boolean haschild;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examsubmmitter.id
     *
     * @return the value of examsubmmitter.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examsubmmitter.id
     *
     * @param id the value for examsubmmitter.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examsubmmitter.ajxh
     *
     * @return the value of examsubmmitter.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examsubmmitter.ajxh
     *
     * @param ajxh the value for examsubmmitter.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examsubmmitter.submitter1
     *
     * @return the value of examsubmmitter.submitter1
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getSubmitter1() {
        return submitter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examsubmmitter.submitter1
     *
     * @param submitter1 the value for examsubmmitter.submitter1
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setSubmitter1(String submitter1) {
        this.submitter1 = submitter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examsubmmitter.submitter2
     *
     * @return the value of examsubmmitter.submitter2
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getSubmitter2() {
        return submitter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examsubmmitter.submitter2
     *
     * @param submitter2 the value for examsubmmitter.submitter2
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setSubmitter2(String submitter2) {
        this.submitter2 = submitter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examsubmmitter.confirmedAll
     *
     * @return the value of examsubmmitter.confirmedAll
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Boolean getConfirmedall() {
        return confirmedall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examsubmmitter.confirmedAll
     *
     * @param confirmedall the value for examsubmmitter.confirmedAll
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setConfirmedall(Boolean confirmedall) {
        this.confirmedall = confirmedall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examsubmmitter.hasChild
     *
     * @return the value of examsubmmitter.hasChild
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Boolean getHaschild() {
        return haschild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examsubmmitter.hasChild
     *
     * @param haschild the value for examsubmmitter.hasChild
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setHaschild(Boolean haschild) {
        this.haschild = haschild;
    }
}