package main.java.generator.po;

public class Fact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fact.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fact.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fact.content
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fact.id
     *
     * @return the value of fact.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fact.id
     *
     * @param id the value for fact.id
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fact.ajxh
     *
     * @return the value of fact.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fact.ajxh
     *
     * @param ajxh the value for fact.ajxh
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fact.content
     *
     * @return the value of fact.content
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fact.content
     *
     * @param content the value for fact.content
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}