package main.java.generator.po;

import java.io.Serializable;

public class Law implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column law.id
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column law.name
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column law.id
	 * @return  the value of law.id
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column law.id
	 * @param id  the value for law.id
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column law.name
	 * @return  the value of law.name
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column law.name
	 * @param name  the value for law.name
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}