package main.java.generator.po;

import java.util.ArrayList;
import java.util.List;

public class LawContentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public LawContentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andChapterIsNull() {
			addCriterion("chapter is null");
			return (Criteria) this;
		}

		public Criteria andChapterIsNotNull() {
			addCriterion("chapter is not null");
			return (Criteria) this;
		}

		public Criteria andChapterEqualTo(Integer value) {
			addCriterion("chapter =", value, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterNotEqualTo(Integer value) {
			addCriterion("chapter <>", value, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterGreaterThan(Integer value) {
			addCriterion("chapter >", value, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterGreaterThanOrEqualTo(Integer value) {
			addCriterion("chapter >=", value, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterLessThan(Integer value) {
			addCriterion("chapter <", value, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterLessThanOrEqualTo(Integer value) {
			addCriterion("chapter <=", value, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterIn(List<Integer> values) {
			addCriterion("chapter in", values, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterNotIn(List<Integer> values) {
			addCriterion("chapter not in", values, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterBetween(Integer value1, Integer value2) {
			addCriterion("chapter between", value1, value2, "chapter");
			return (Criteria) this;
		}

		public Criteria andChapterNotBetween(Integer value1, Integer value2) {
			addCriterion("chapter not between", value1, value2, "chapter");
			return (Criteria) this;
		}

		public Criteria andSectionIsNull() {
			addCriterion("section is null");
			return (Criteria) this;
		}

		public Criteria andSectionIsNotNull() {
			addCriterion("section is not null");
			return (Criteria) this;
		}

		public Criteria andSectionEqualTo(Integer value) {
			addCriterion("section =", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionNotEqualTo(Integer value) {
			addCriterion("section <>", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionGreaterThan(Integer value) {
			addCriterion("section >", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionGreaterThanOrEqualTo(Integer value) {
			addCriterion("section >=", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionLessThan(Integer value) {
			addCriterion("section <", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionLessThanOrEqualTo(Integer value) {
			addCriterion("section <=", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionIn(List<Integer> values) {
			addCriterion("section in", values, "section");
			return (Criteria) this;
		}

		public Criteria andSectionNotIn(List<Integer> values) {
			addCriterion("section not in", values, "section");
			return (Criteria) this;
		}

		public Criteria andSectionBetween(Integer value1, Integer value2) {
			addCriterion("section between", value1, value2, "section");
			return (Criteria) this;
		}

		public Criteria andSectionNotBetween(Integer value1, Integer value2) {
			addCriterion("section not between", value1, value2, "section");
			return (Criteria) this;
		}

		public Criteria andItemIsNull() {
			addCriterion("item is null");
			return (Criteria) this;
		}

		public Criteria andItemIsNotNull() {
			addCriterion("item is not null");
			return (Criteria) this;
		}

		public Criteria andItemEqualTo(Integer value) {
			addCriterion("item =", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemNotEqualTo(Integer value) {
			addCriterion("item <>", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemGreaterThan(Integer value) {
			addCriterion("item >", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemGreaterThanOrEqualTo(Integer value) {
			addCriterion("item >=", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemLessThan(Integer value) {
			addCriterion("item <", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemLessThanOrEqualTo(Integer value) {
			addCriterion("item <=", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemIn(List<Integer> values) {
			addCriterion("item in", values, "item");
			return (Criteria) this;
		}

		public Criteria andItemNotIn(List<Integer> values) {
			addCriterion("item not in", values, "item");
			return (Criteria) this;
		}

		public Criteria andItemBetween(Integer value1, Integer value2) {
			addCriterion("item between", value1, value2, "item");
			return (Criteria) this;
		}

		public Criteria andItemNotBetween(Integer value1, Integer value2) {
			addCriterion("item not between", value1, value2, "item");
			return (Criteria) this;
		}

		public Criteria andLawidIsNull() {
			addCriterion("lawId is null");
			return (Criteria) this;
		}

		public Criteria andLawidIsNotNull() {
			addCriterion("lawId is not null");
			return (Criteria) this;
		}

		public Criteria andLawidEqualTo(String value) {
			addCriterion("lawId =", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidNotEqualTo(String value) {
			addCriterion("lawId <>", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidGreaterThan(String value) {
			addCriterion("lawId >", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidGreaterThanOrEqualTo(String value) {
			addCriterion("lawId >=", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidLessThan(String value) {
			addCriterion("lawId <", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidLessThanOrEqualTo(String value) {
			addCriterion("lawId <=", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidLike(String value) {
			addCriterion("lawId like", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidNotLike(String value) {
			addCriterion("lawId not like", value, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidIn(List<String> values) {
			addCriterion("lawId in", values, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidNotIn(List<String> values) {
			addCriterion("lawId not in", values, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidBetween(String value1, String value2) {
			addCriterion("lawId between", value1, value2, "lawid");
			return (Criteria) this;
		}

		public Criteria andLawidNotBetween(String value1, String value2) {
			addCriterion("lawId not between", value1, value2, "lawid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table lawcontent
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lawcontent
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 26 19:19:59 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}