package main.java.generator.po;

public class LawContent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lawcontent.id
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lawcontent.version
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lawcontent.chapter
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private Integer chapter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lawcontent.section
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private Integer section;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lawcontent.item
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private Integer item;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lawcontent.lawId
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private String lawid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lawcontent.content
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lawcontent.id
	 * @return  the value of lawcontent.id
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lawcontent.id
	 * @param id  the value for lawcontent.id
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lawcontent.version
	 * @return  the value of lawcontent.version
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lawcontent.version
	 * @param version  the value for lawcontent.version
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lawcontent.chapter
	 * @return  the value of lawcontent.chapter
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public Integer getChapter() {
		return chapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lawcontent.chapter
	 * @param chapter  the value for lawcontent.chapter
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setChapter(Integer chapter) {
		this.chapter = chapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lawcontent.section
	 * @return  the value of lawcontent.section
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public Integer getSection() {
		return section;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lawcontent.section
	 * @param section  the value for lawcontent.section
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setSection(Integer section) {
		this.section = section;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lawcontent.item
	 * @return  the value of lawcontent.item
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public Integer getItem() {
		return item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lawcontent.item
	 * @param item  the value for lawcontent.item
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setItem(Integer item) {
		this.item = item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lawcontent.lawId
	 * @return  the value of lawcontent.lawId
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public String getLawid() {
		return lawid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lawcontent.lawId
	 * @param lawid  the value for lawcontent.lawId
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setLawid(String lawid) {
		this.lawid = lawid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lawcontent.content
	 * @return  the value of lawcontent.content
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lawcontent.content
	 * @param content  the value for lawcontent.content
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}
}