package main.java.generator.po;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private Integer role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.valid
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private Boolean valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.court
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private String court;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.lastLoginIp
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private String lastloginip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.lastLoginTime
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private Date lastlogintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.creatAt
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private Date creatat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.deleteAt
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	private Date deleteat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role
	 * @return  the value of user.role
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role
	 * @param role  the value for user.role
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.valid
	 * @return  the value of user.valid
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.valid
	 * @param valid  the value for user.valid
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.court
	 * @return  the value of user.court
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public String getCourt() {
		return court;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.court
	 * @param court  the value for user.court
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setCourt(String court) {
		this.court = court;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.lastLoginIp
	 * @return  the value of user.lastLoginIp
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public String getLastloginip() {
		return lastloginip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.lastLoginIp
	 * @param lastloginip  the value for user.lastLoginIp
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setLastloginip(String lastloginip) {
		this.lastloginip = lastloginip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.lastLoginTime
	 * @return  the value of user.lastLoginTime
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public Date getLastlogintime() {
		return lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.lastLoginTime
	 * @param lastlogintime  the value for user.lastLoginTime
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setLastlogintime(Date lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.creatAt
	 * @return  the value of user.creatAt
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public Date getCreatat() {
		return creatat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.creatAt
	 * @param creatat  the value for user.creatAt
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setCreatat(Date creatat) {
		this.creatat = creatat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.deleteAt
	 * @return  the value of user.deleteAt
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public Date getDeleteat() {
		return deleteat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.deleteAt
	 * @param deleteat  the value for user.deleteAt
	 * @mbg.generated  Sat May 13 15:50:49 CST 2017
	 */
	public void setDeleteat(Date deleteat) {
		this.deleteat = deleteat;
	}
}