package main.java.generator.po;

import java.util.ArrayList;
import java.util.List;

public class WsAjjbxxbExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public WsAjjbxxbExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAjxhIsNull() {
            addCriterion("AJXH is null");
            return (Criteria) this;
        }

        public Criteria andAjxhIsNotNull() {
            addCriterion("AJXH is not null");
            return (Criteria) this;
        }

        public Criteria andAjxhEqualTo(Integer value) {
            addCriterion("AJXH =", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhNotEqualTo(Integer value) {
            addCriterion("AJXH <>", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhGreaterThan(Integer value) {
            addCriterion("AJXH >", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhGreaterThanOrEqualTo(Integer value) {
            addCriterion("AJXH >=", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhLessThan(Integer value) {
            addCriterion("AJXH <", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhLessThanOrEqualTo(Integer value) {
            addCriterion("AJXH <=", value, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhIn(List<Integer> values) {
            addCriterion("AJXH in", values, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhNotIn(List<Integer> values) {
            addCriterion("AJXH not in", values, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhBetween(Integer value1, Integer value2) {
            addCriterion("AJXH between", value1, value2, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAjxhNotBetween(Integer value1, Integer value2) {
            addCriterion("AJXH not between", value1, value2, "ajxh");
            return (Criteria) this;
        }

        public Criteria andAhIsNull() {
            addCriterion("AH is null");
            return (Criteria) this;
        }

        public Criteria andAhIsNotNull() {
            addCriterion("AH is not null");
            return (Criteria) this;
        }

        public Criteria andAhEqualTo(String value) {
            addCriterion("AH =", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhNotEqualTo(String value) {
            addCriterion("AH <>", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhGreaterThan(String value) {
            addCriterion("AH >", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhGreaterThanOrEqualTo(String value) {
            addCriterion("AH >=", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhLessThan(String value) {
            addCriterion("AH <", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhLessThanOrEqualTo(String value) {
            addCriterion("AH <=", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhLike(String value) {
            addCriterion("AH like", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhNotLike(String value) {
            addCriterion("AH not like", value, "ah");
            return (Criteria) this;
        }

        public Criteria andAhIn(List<String> values) {
            addCriterion("AH in", values, "ah");
            return (Criteria) this;
        }

        public Criteria andAhNotIn(List<String> values) {
            addCriterion("AH not in", values, "ah");
            return (Criteria) this;
        }

        public Criteria andAhBetween(String value1, String value2) {
            addCriterion("AH between", value1, value2, "ah");
            return (Criteria) this;
        }

        public Criteria andAhNotBetween(String value1, String value2) {
            addCriterion("AH not between", value1, value2, "ah");
            return (Criteria) this;
        }

        public Criteria andAjxzIsNull() {
            addCriterion("AJXZ is null");
            return (Criteria) this;
        }

        public Criteria andAjxzIsNotNull() {
            addCriterion("AJXZ is not null");
            return (Criteria) this;
        }

        public Criteria andAjxzEqualTo(String value) {
            addCriterion("AJXZ =", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzNotEqualTo(String value) {
            addCriterion("AJXZ <>", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzGreaterThan(String value) {
            addCriterion("AJXZ >", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzGreaterThanOrEqualTo(String value) {
            addCriterion("AJXZ >=", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzLessThan(String value) {
            addCriterion("AJXZ <", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzLessThanOrEqualTo(String value) {
            addCriterion("AJXZ <=", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzLike(String value) {
            addCriterion("AJXZ like", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzNotLike(String value) {
            addCriterion("AJXZ not like", value, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzIn(List<String> values) {
            addCriterion("AJXZ in", values, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzNotIn(List<String> values) {
            addCriterion("AJXZ not in", values, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzBetween(String value1, String value2) {
            addCriterion("AJXZ between", value1, value2, "ajxz");
            return (Criteria) this;
        }

        public Criteria andAjxzNotBetween(String value1, String value2) {
            addCriterion("AJXZ not between", value1, value2, "ajxz");
            return (Criteria) this;
        }

        public Criteria andSpcxIsNull() {
            addCriterion("SPCX is null");
            return (Criteria) this;
        }

        public Criteria andSpcxIsNotNull() {
            addCriterion("SPCX is not null");
            return (Criteria) this;
        }

        public Criteria andSpcxEqualTo(String value) {
            addCriterion("SPCX =", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxNotEqualTo(String value) {
            addCriterion("SPCX <>", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxGreaterThan(String value) {
            addCriterion("SPCX >", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxGreaterThanOrEqualTo(String value) {
            addCriterion("SPCX >=", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxLessThan(String value) {
            addCriterion("SPCX <", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxLessThanOrEqualTo(String value) {
            addCriterion("SPCX <=", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxLike(String value) {
            addCriterion("SPCX like", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxNotLike(String value) {
            addCriterion("SPCX not like", value, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxIn(List<String> values) {
            addCriterion("SPCX in", values, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxNotIn(List<String> values) {
            addCriterion("SPCX not in", values, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxBetween(String value1, String value2) {
            addCriterion("SPCX between", value1, value2, "spcx");
            return (Criteria) this;
        }

        public Criteria andSpcxNotBetween(String value1, String value2) {
            addCriterion("SPCX not between", value1, value2, "spcx");
            return (Criteria) this;
        }

        public Criteria andWsmcIsNull() {
            addCriterion("WSMC is null");
            return (Criteria) this;
        }

        public Criteria andWsmcIsNotNull() {
            addCriterion("WSMC is not null");
            return (Criteria) this;
        }

        public Criteria andWsmcEqualTo(String value) {
            addCriterion("WSMC =", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcNotEqualTo(String value) {
            addCriterion("WSMC <>", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcGreaterThan(String value) {
            addCriterion("WSMC >", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcGreaterThanOrEqualTo(String value) {
            addCriterion("WSMC >=", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcLessThan(String value) {
            addCriterion("WSMC <", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcLessThanOrEqualTo(String value) {
            addCriterion("WSMC <=", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcLike(String value) {
            addCriterion("WSMC like", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcNotLike(String value) {
            addCriterion("WSMC not like", value, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcIn(List<String> values) {
            addCriterion("WSMC in", values, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcNotIn(List<String> values) {
            addCriterion("WSMC not in", values, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcBetween(String value1, String value2) {
            addCriterion("WSMC between", value1, value2, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWsmcNotBetween(String value1, String value2) {
            addCriterion("WSMC not between", value1, value2, "wsmc");
            return (Criteria) this;
        }

        public Criteria andWszlIsNull() {
            addCriterion("WSZL is null");
            return (Criteria) this;
        }

        public Criteria andWszlIsNotNull() {
            addCriterion("WSZL is not null");
            return (Criteria) this;
        }

        public Criteria andWszlEqualTo(String value) {
            addCriterion("WSZL =", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlNotEqualTo(String value) {
            addCriterion("WSZL <>", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlGreaterThan(String value) {
            addCriterion("WSZL >", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlGreaterThanOrEqualTo(String value) {
            addCriterion("WSZL >=", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlLessThan(String value) {
            addCriterion("WSZL <", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlLessThanOrEqualTo(String value) {
            addCriterion("WSZL <=", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlLike(String value) {
            addCriterion("WSZL like", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlNotLike(String value) {
            addCriterion("WSZL not like", value, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlIn(List<String> values) {
            addCriterion("WSZL in", values, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlNotIn(List<String> values) {
            addCriterion("WSZL not in", values, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlBetween(String value1, String value2) {
            addCriterion("WSZL between", value1, value2, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszlNotBetween(String value1, String value2) {
            addCriterion("WSZL not between", value1, value2, "wszl");
            return (Criteria) this;
        }

        public Criteria andWszzdwIsNull() {
            addCriterion("WSZZDW is null");
            return (Criteria) this;
        }

        public Criteria andWszzdwIsNotNull() {
            addCriterion("WSZZDW is not null");
            return (Criteria) this;
        }

        public Criteria andWszzdwEqualTo(String value) {
            addCriterion("WSZZDW =", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwNotEqualTo(String value) {
            addCriterion("WSZZDW <>", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwGreaterThan(String value) {
            addCriterion("WSZZDW >", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwGreaterThanOrEqualTo(String value) {
            addCriterion("WSZZDW >=", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwLessThan(String value) {
            addCriterion("WSZZDW <", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwLessThanOrEqualTo(String value) {
            addCriterion("WSZZDW <=", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwLike(String value) {
            addCriterion("WSZZDW like", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwNotLike(String value) {
            addCriterion("WSZZDW not like", value, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwIn(List<String> values) {
            addCriterion("WSZZDW in", values, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwNotIn(List<String> values) {
            addCriterion("WSZZDW not in", values, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwBetween(String value1, String value2) {
            addCriterion("WSZZDW between", value1, value2, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andWszzdwNotBetween(String value1, String value2) {
            addCriterion("WSZZDW not between", value1, value2, "wszzdw");
            return (Criteria) this;
        }

        public Criteria andJbfyIsNull() {
            addCriterion("JBFY is null");
            return (Criteria) this;
        }

        public Criteria andJbfyIsNotNull() {
            addCriterion("JBFY is not null");
            return (Criteria) this;
        }

        public Criteria andJbfyEqualTo(String value) {
            addCriterion("JBFY =", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyNotEqualTo(String value) {
            addCriterion("JBFY <>", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyGreaterThan(String value) {
            addCriterion("JBFY >", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyGreaterThanOrEqualTo(String value) {
            addCriterion("JBFY >=", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyLessThan(String value) {
            addCriterion("JBFY <", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyLessThanOrEqualTo(String value) {
            addCriterion("JBFY <=", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyLike(String value) {
            addCriterion("JBFY like", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyNotLike(String value) {
            addCriterion("JBFY not like", value, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyIn(List<String> values) {
            addCriterion("JBFY in", values, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyNotIn(List<String> values) {
            addCriterion("JBFY not in", values, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyBetween(String value1, String value2) {
            addCriterion("JBFY between", value1, value2, "jbfy");
            return (Criteria) this;
        }

        public Criteria andJbfyNotBetween(String value1, String value2) {
            addCriterion("JBFY not between", value1, value2, "jbfy");
            return (Criteria) this;
        }

        public Criteria andFyjbIsNull() {
            addCriterion("FYJB is null");
            return (Criteria) this;
        }

        public Criteria andFyjbIsNotNull() {
            addCriterion("FYJB is not null");
            return (Criteria) this;
        }

        public Criteria andFyjbEqualTo(String value) {
            addCriterion("FYJB =", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbNotEqualTo(String value) {
            addCriterion("FYJB <>", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbGreaterThan(String value) {
            addCriterion("FYJB >", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbGreaterThanOrEqualTo(String value) {
            addCriterion("FYJB >=", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbLessThan(String value) {
            addCriterion("FYJB <", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbLessThanOrEqualTo(String value) {
            addCriterion("FYJB <=", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbLike(String value) {
            addCriterion("FYJB like", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbNotLike(String value) {
            addCriterion("FYJB not like", value, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbIn(List<String> values) {
            addCriterion("FYJB in", values, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbNotIn(List<String> values) {
            addCriterion("FYJB not in", values, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbBetween(String value1, String value2) {
            addCriterion("FYJB between", value1, value2, "fyjb");
            return (Criteria) this;
        }

        public Criteria andFyjbNotBetween(String value1, String value2) {
            addCriterion("FYJB not between", value1, value2, "fyjb");
            return (Criteria) this;
        }

        public Criteria andXzqhshIsNull() {
            addCriterion("XZQHSH is null");
            return (Criteria) this;
        }

        public Criteria andXzqhshIsNotNull() {
            addCriterion("XZQHSH is not null");
            return (Criteria) this;
        }

        public Criteria andXzqhshEqualTo(String value) {
            addCriterion("XZQHSH =", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshNotEqualTo(String value) {
            addCriterion("XZQHSH <>", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshGreaterThan(String value) {
            addCriterion("XZQHSH >", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshGreaterThanOrEqualTo(String value) {
            addCriterion("XZQHSH >=", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshLessThan(String value) {
            addCriterion("XZQHSH <", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshLessThanOrEqualTo(String value) {
            addCriterion("XZQHSH <=", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshLike(String value) {
            addCriterion("XZQHSH like", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshNotLike(String value) {
            addCriterion("XZQHSH not like", value, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshIn(List<String> values) {
            addCriterion("XZQHSH in", values, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshNotIn(List<String> values) {
            addCriterion("XZQHSH not in", values, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshBetween(String value1, String value2) {
            addCriterion("XZQHSH between", value1, value2, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhshNotBetween(String value1, String value2) {
            addCriterion("XZQHSH not between", value1, value2, "xzqhsh");
            return (Criteria) this;
        }

        public Criteria andXzqhsIsNull() {
            addCriterion("XZQHS is null");
            return (Criteria) this;
        }

        public Criteria andXzqhsIsNotNull() {
            addCriterion("XZQHS is not null");
            return (Criteria) this;
        }

        public Criteria andXzqhsEqualTo(String value) {
            addCriterion("XZQHS =", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsNotEqualTo(String value) {
            addCriterion("XZQHS <>", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsGreaterThan(String value) {
            addCriterion("XZQHS >", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsGreaterThanOrEqualTo(String value) {
            addCriterion("XZQHS >=", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsLessThan(String value) {
            addCriterion("XZQHS <", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsLessThanOrEqualTo(String value) {
            addCriterion("XZQHS <=", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsLike(String value) {
            addCriterion("XZQHS like", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsNotLike(String value) {
            addCriterion("XZQHS not like", value, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsIn(List<String> values) {
            addCriterion("XZQHS in", values, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsNotIn(List<String> values) {
            addCriterion("XZQHS not in", values, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsBetween(String value1, String value2) {
            addCriterion("XZQHS between", value1, value2, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andXzqhsNotBetween(String value1, String value2) {
            addCriterion("XZQHS not between", value1, value2, "xzqhs");
            return (Criteria) this;
        }

        public Criteria andLandIsNull() {
            addCriterion("LAND is null");
            return (Criteria) this;
        }

        public Criteria andLandIsNotNull() {
            addCriterion("LAND is not null");
            return (Criteria) this;
        }

        public Criteria andLandEqualTo(String value) {
            addCriterion("LAND =", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandNotEqualTo(String value) {
            addCriterion("LAND <>", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandGreaterThan(String value) {
            addCriterion("LAND >", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandGreaterThanOrEqualTo(String value) {
            addCriterion("LAND >=", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandLessThan(String value) {
            addCriterion("LAND <", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandLessThanOrEqualTo(String value) {
            addCriterion("LAND <=", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandLike(String value) {
            addCriterion("LAND like", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandNotLike(String value) {
            addCriterion("LAND not like", value, "land");
            return (Criteria) this;
        }

        public Criteria andLandIn(List<String> values) {
            addCriterion("LAND in", values, "land");
            return (Criteria) this;
        }

        public Criteria andLandNotIn(List<String> values) {
            addCriterion("LAND not in", values, "land");
            return (Criteria) this;
        }

        public Criteria andLandBetween(String value1, String value2) {
            addCriterion("LAND between", value1, value2, "land");
            return (Criteria) this;
        }

        public Criteria andLandNotBetween(String value1, String value2) {
            addCriterion("LAND not between", value1, value2, "land");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyIsNull() {
            addCriterion("TCGXQYY is null");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyIsNotNull() {
            addCriterion("TCGXQYY is not null");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyEqualTo(String value) {
            addCriterion("TCGXQYY =", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyNotEqualTo(String value) {
            addCriterion("TCGXQYY <>", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyGreaterThan(String value) {
            addCriterion("TCGXQYY >", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyGreaterThanOrEqualTo(String value) {
            addCriterion("TCGXQYY >=", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyLessThan(String value) {
            addCriterion("TCGXQYY <", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyLessThanOrEqualTo(String value) {
            addCriterion("TCGXQYY <=", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyLike(String value) {
            addCriterion("TCGXQYY like", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyNotLike(String value) {
            addCriterion("TCGXQYY not like", value, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyIn(List<String> values) {
            addCriterion("TCGXQYY in", values, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyNotIn(List<String> values) {
            addCriterion("TCGXQYY not in", values, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyBetween(String value1, String value2) {
            addCriterion("TCGXQYY between", value1, value2, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andTcgxqyyNotBetween(String value1, String value2) {
            addCriterion("TCGXQYY not between", value1, value2, "tcgxqyy");
            return (Criteria) this;
        }

        public Criteria andJafsIsNull() {
            addCriterion("JAFS is null");
            return (Criteria) this;
        }

        public Criteria andJafsIsNotNull() {
            addCriterion("JAFS is not null");
            return (Criteria) this;
        }

        public Criteria andJafsEqualTo(String value) {
            addCriterion("JAFS =", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotEqualTo(String value) {
            addCriterion("JAFS <>", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsGreaterThan(String value) {
            addCriterion("JAFS >", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsGreaterThanOrEqualTo(String value) {
            addCriterion("JAFS >=", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsLessThan(String value) {
            addCriterion("JAFS <", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsLessThanOrEqualTo(String value) {
            addCriterion("JAFS <=", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsLike(String value) {
            addCriterion("JAFS like", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotLike(String value) {
            addCriterion("JAFS not like", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsIn(List<String> values) {
            addCriterion("JAFS in", values, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotIn(List<String> values) {
            addCriterion("JAFS not in", values, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsBetween(String value1, String value2) {
            addCriterion("JAFS between", value1, value2, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotBetween(String value1, String value2) {
            addCriterion("JAFS not between", value1, value2, "jafs");
            return (Criteria) this;
        }

        public Criteria andPjsjIsNull() {
            addCriterion("PJSJ is null");
            return (Criteria) this;
        }

        public Criteria andPjsjIsNotNull() {
            addCriterion("PJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andPjsjEqualTo(String value) {
            addCriterion("PJSJ =", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjNotEqualTo(String value) {
            addCriterion("PJSJ <>", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjGreaterThan(String value) {
            addCriterion("PJSJ >", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjGreaterThanOrEqualTo(String value) {
            addCriterion("PJSJ >=", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjLessThan(String value) {
            addCriterion("PJSJ <", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjLessThanOrEqualTo(String value) {
            addCriterion("PJSJ <=", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjLike(String value) {
            addCriterion("PJSJ like", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjNotLike(String value) {
            addCriterion("PJSJ not like", value, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjIn(List<String> values) {
            addCriterion("PJSJ in", values, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjNotIn(List<String> values) {
            addCriterion("PJSJ not in", values, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjBetween(String value1, String value2) {
            addCriterion("PJSJ between", value1, value2, "pjsj");
            return (Criteria) this;
        }

        public Criteria andPjsjNotBetween(String value1, String value2) {
            addCriterion("PJSJ not between", value1, value2, "pjsj");
            return (Criteria) this;
        }

        public Criteria andJandIsNull() {
            addCriterion("JAND is null");
            return (Criteria) this;
        }

        public Criteria andJandIsNotNull() {
            addCriterion("JAND is not null");
            return (Criteria) this;
        }

        public Criteria andJandEqualTo(String value) {
            addCriterion("JAND =", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandNotEqualTo(String value) {
            addCriterion("JAND <>", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandGreaterThan(String value) {
            addCriterion("JAND >", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandGreaterThanOrEqualTo(String value) {
            addCriterion("JAND >=", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandLessThan(String value) {
            addCriterion("JAND <", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandLessThanOrEqualTo(String value) {
            addCriterion("JAND <=", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandLike(String value) {
            addCriterion("JAND like", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandNotLike(String value) {
            addCriterion("JAND not like", value, "jand");
            return (Criteria) this;
        }

        public Criteria andJandIn(List<String> values) {
            addCriterion("JAND in", values, "jand");
            return (Criteria) this;
        }

        public Criteria andJandNotIn(List<String> values) {
            addCriterion("JAND not in", values, "jand");
            return (Criteria) this;
        }

        public Criteria andJandBetween(String value1, String value2) {
            addCriterion("JAND between", value1, value2, "jand");
            return (Criteria) this;
        }

        public Criteria andJandNotBetween(String value1, String value2) {
            addCriterion("JAND not between", value1, value2, "jand");
            return (Criteria) this;
        }

        public Criteria andJayfIsNull() {
            addCriterion("JAYF is null");
            return (Criteria) this;
        }

        public Criteria andJayfIsNotNull() {
            addCriterion("JAYF is not null");
            return (Criteria) this;
        }

        public Criteria andJayfEqualTo(String value) {
            addCriterion("JAYF =", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfNotEqualTo(String value) {
            addCriterion("JAYF <>", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfGreaterThan(String value) {
            addCriterion("JAYF >", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfGreaterThanOrEqualTo(String value) {
            addCriterion("JAYF >=", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfLessThan(String value) {
            addCriterion("JAYF <", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfLessThanOrEqualTo(String value) {
            addCriterion("JAYF <=", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfLike(String value) {
            addCriterion("JAYF like", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfNotLike(String value) {
            addCriterion("JAYF not like", value, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfIn(List<String> values) {
            addCriterion("JAYF in", values, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfNotIn(List<String> values) {
            addCriterion("JAYF not in", values, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfBetween(String value1, String value2) {
            addCriterion("JAYF between", value1, value2, "jayf");
            return (Criteria) this;
        }

        public Criteria andJayfNotBetween(String value1, String value2) {
            addCriterion("JAYF not between", value1, value2, "jayf");
            return (Criteria) this;
        }

        public Criteria andKsszIsNull() {
            addCriterion("KSSZ is null");
            return (Criteria) this;
        }

        public Criteria andKsszIsNotNull() {
            addCriterion("KSSZ is not null");
            return (Criteria) this;
        }

        public Criteria andKsszEqualTo(String value) {
            addCriterion("KSSZ =", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszNotEqualTo(String value) {
            addCriterion("KSSZ <>", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszGreaterThan(String value) {
            addCriterion("KSSZ >", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszGreaterThanOrEqualTo(String value) {
            addCriterion("KSSZ >=", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszLessThan(String value) {
            addCriterion("KSSZ <", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszLessThanOrEqualTo(String value) {
            addCriterion("KSSZ <=", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszLike(String value) {
            addCriterion("KSSZ like", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszNotLike(String value) {
            addCriterion("KSSZ not like", value, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszIn(List<String> values) {
            addCriterion("KSSZ in", values, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszNotIn(List<String> values) {
            addCriterion("KSSZ not in", values, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszBetween(String value1, String value2) {
            addCriterion("KSSZ between", value1, value2, "kssz");
            return (Criteria) this;
        }

        public Criteria andKsszNotBetween(String value1, String value2) {
            addCriterion("KSSZ not between", value1, value2, "kssz");
            return (Criteria) this;
        }

        public Criteria andSsqxIsNull() {
            addCriterion("SSQX is null");
            return (Criteria) this;
        }

        public Criteria andSsqxIsNotNull() {
            addCriterion("SSQX is not null");
            return (Criteria) this;
        }

        public Criteria andSsqxEqualTo(String value) {
            addCriterion("SSQX =", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxNotEqualTo(String value) {
            addCriterion("SSQX <>", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxGreaterThan(String value) {
            addCriterion("SSQX >", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxGreaterThanOrEqualTo(String value) {
            addCriterion("SSQX >=", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxLessThan(String value) {
            addCriterion("SSQX <", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxLessThanOrEqualTo(String value) {
            addCriterion("SSQX <=", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxLike(String value) {
            addCriterion("SSQX like", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxNotLike(String value) {
            addCriterion("SSQX not like", value, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxIn(List<String> values) {
            addCriterion("SSQX in", values, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxNotIn(List<String> values) {
            addCriterion("SSQX not in", values, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxBetween(String value1, String value2) {
            addCriterion("SSQX between", value1, value2, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSsqxNotBetween(String value1, String value2) {
            addCriterion("SSQX not between", value1, value2, "ssqx");
            return (Criteria) this;
        }

        public Criteria andSstjclIsNull() {
            addCriterion("SSTJCL is null");
            return (Criteria) this;
        }

        public Criteria andSstjclIsNotNull() {
            addCriterion("SSTJCL is not null");
            return (Criteria) this;
        }

        public Criteria andSstjclEqualTo(String value) {
            addCriterion("SSTJCL =", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclNotEqualTo(String value) {
            addCriterion("SSTJCL <>", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclGreaterThan(String value) {
            addCriterion("SSTJCL >", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclGreaterThanOrEqualTo(String value) {
            addCriterion("SSTJCL >=", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclLessThan(String value) {
            addCriterion("SSTJCL <", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclLessThanOrEqualTo(String value) {
            addCriterion("SSTJCL <=", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclLike(String value) {
            addCriterion("SSTJCL like", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclNotLike(String value) {
            addCriterion("SSTJCL not like", value, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclIn(List<String> values) {
            addCriterion("SSTJCL in", values, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclNotIn(List<String> values) {
            addCriterion("SSTJCL not in", values, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclBetween(String value1, String value2) {
            addCriterion("SSTJCL between", value1, value2, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSstjclNotBetween(String value1, String value2) {
            addCriterion("SSTJCL not between", value1, value2, "sstjcl");
            return (Criteria) this;
        }

        public Criteria andSffhcsIsNull() {
            addCriterion("SFFHCS is null");
            return (Criteria) this;
        }

        public Criteria andSffhcsIsNotNull() {
            addCriterion("SFFHCS is not null");
            return (Criteria) this;
        }

        public Criteria andSffhcsEqualTo(String value) {
            addCriterion("SFFHCS =", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsNotEqualTo(String value) {
            addCriterion("SFFHCS <>", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsGreaterThan(String value) {
            addCriterion("SFFHCS >", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsGreaterThanOrEqualTo(String value) {
            addCriterion("SFFHCS >=", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsLessThan(String value) {
            addCriterion("SFFHCS <", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsLessThanOrEqualTo(String value) {
            addCriterion("SFFHCS <=", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsLike(String value) {
            addCriterion("SFFHCS like", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsNotLike(String value) {
            addCriterion("SFFHCS not like", value, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsIn(List<String> values) {
            addCriterion("SFFHCS in", values, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsNotIn(List<String> values) {
            addCriterion("SFFHCS not in", values, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsBetween(String value1, String value2) {
            addCriterion("SFFHCS between", value1, value2, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andSffhcsNotBetween(String value1, String value2) {
            addCriterion("SFFHCS not between", value1, value2, "sffhcs");
            return (Criteria) this;
        }

        public Criteria andFhcsyyIsNull() {
            addCriterion("FHCSYY is null");
            return (Criteria) this;
        }

        public Criteria andFhcsyyIsNotNull() {
            addCriterion("FHCSYY is not null");
            return (Criteria) this;
        }

        public Criteria andFhcsyyEqualTo(String value) {
            addCriterion("FHCSYY =", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyNotEqualTo(String value) {
            addCriterion("FHCSYY <>", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyGreaterThan(String value) {
            addCriterion("FHCSYY >", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyGreaterThanOrEqualTo(String value) {
            addCriterion("FHCSYY >=", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyLessThan(String value) {
            addCriterion("FHCSYY <", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyLessThanOrEqualTo(String value) {
            addCriterion("FHCSYY <=", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyLike(String value) {
            addCriterion("FHCSYY like", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyNotLike(String value) {
            addCriterion("FHCSYY not like", value, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyIn(List<String> values) {
            addCriterion("FHCSYY in", values, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyNotIn(List<String> values) {
            addCriterion("FHCSYY not in", values, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyBetween(String value1, String value2) {
            addCriterion("FHCSYY between", value1, value2, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andFhcsyyNotBetween(String value1, String value2) {
            addCriterion("FHCSYY not between", value1, value2, "fhcsyy");
            return (Criteria) this;
        }

        public Criteria andJazbdIsNull() {
            addCriterion("JAZBD is null");
            return (Criteria) this;
        }

        public Criteria andJazbdIsNotNull() {
            addCriterion("JAZBD is not null");
            return (Criteria) this;
        }

        public Criteria andJazbdEqualTo(String value) {
            addCriterion("JAZBD =", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdNotEqualTo(String value) {
            addCriterion("JAZBD <>", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdGreaterThan(String value) {
            addCriterion("JAZBD >", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdGreaterThanOrEqualTo(String value) {
            addCriterion("JAZBD >=", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdLessThan(String value) {
            addCriterion("JAZBD <", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdLessThanOrEqualTo(String value) {
            addCriterion("JAZBD <=", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdLike(String value) {
            addCriterion("JAZBD like", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdNotLike(String value) {
            addCriterion("JAZBD not like", value, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdIn(List<String> values) {
            addCriterion("JAZBD in", values, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdNotIn(List<String> values) {
            addCriterion("JAZBD not in", values, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdBetween(String value1, String value2) {
            addCriterion("JAZBD between", value1, value2, "jazbd");
            return (Criteria) this;
        }

        public Criteria andJazbdNotBetween(String value1, String value2) {
            addCriterion("JAZBD not between", value1, value2, "jazbd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 20 16:55:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}