package main.java.generator.po;

public class WsAjjbxxb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.AJXH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.AH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String ah;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.AJXZ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String ajxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.SPCX
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String spcx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.WSMC
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String wsmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.WSZL
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String wszl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.WSZZDW
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String wszzdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.JBFY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String jbfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.FYJB
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String fyjb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.XZQHSH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String xzqhsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.XZQHS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String xzqhs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.LAND
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String land;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.TCGXQYY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String tcgxqyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.JAFS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String jafs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.PJSJ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String pjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.JAND
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String jand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.JAYF
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String jayf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.KSSZ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String kssz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.SSQX
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String ssqx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.SSTJCL
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String sstjcl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.SFFHCS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String sffhcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.FHCSYY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String fhcsyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_ajjbxxb.JAZBD
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    private String jazbd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.AJXH
     *
     * @return the value of ws_ajjbxxb.AJXH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.AJXH
     *
     * @param ajxh the value for ws_ajjbxxb.AJXH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.AH
     *
     * @return the value of ws_ajjbxxb.AH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getAh() {
        return ah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.AH
     *
     * @param ah the value for ws_ajjbxxb.AH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setAh(String ah) {
        this.ah = ah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.AJXZ
     *
     * @return the value of ws_ajjbxxb.AJXZ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getAjxz() {
        return ajxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.AJXZ
     *
     * @param ajxz the value for ws_ajjbxxb.AJXZ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setAjxz(String ajxz) {
        this.ajxz = ajxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.SPCX
     *
     * @return the value of ws_ajjbxxb.SPCX
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getSpcx() {
        return spcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.SPCX
     *
     * @param spcx the value for ws_ajjbxxb.SPCX
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setSpcx(String spcx) {
        this.spcx = spcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.WSMC
     *
     * @return the value of ws_ajjbxxb.WSMC
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getWsmc() {
        return wsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.WSMC
     *
     * @param wsmc the value for ws_ajjbxxb.WSMC
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setWsmc(String wsmc) {
        this.wsmc = wsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.WSZL
     *
     * @return the value of ws_ajjbxxb.WSZL
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getWszl() {
        return wszl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.WSZL
     *
     * @param wszl the value for ws_ajjbxxb.WSZL
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setWszl(String wszl) {
        this.wszl = wszl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.WSZZDW
     *
     * @return the value of ws_ajjbxxb.WSZZDW
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getWszzdw() {
        return wszzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.WSZZDW
     *
     * @param wszzdw the value for ws_ajjbxxb.WSZZDW
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setWszzdw(String wszzdw) {
        this.wszzdw = wszzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.JBFY
     *
     * @return the value of ws_ajjbxxb.JBFY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getJbfy() {
        return jbfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.JBFY
     *
     * @param jbfy the value for ws_ajjbxxb.JBFY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setJbfy(String jbfy) {
        this.jbfy = jbfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.FYJB
     *
     * @return the value of ws_ajjbxxb.FYJB
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getFyjb() {
        return fyjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.FYJB
     *
     * @param fyjb the value for ws_ajjbxxb.FYJB
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setFyjb(String fyjb) {
        this.fyjb = fyjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.XZQHSH
     *
     * @return the value of ws_ajjbxxb.XZQHSH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getXzqhsh() {
        return xzqhsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.XZQHSH
     *
     * @param xzqhsh the value for ws_ajjbxxb.XZQHSH
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setXzqhsh(String xzqhsh) {
        this.xzqhsh = xzqhsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.XZQHS
     *
     * @return the value of ws_ajjbxxb.XZQHS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getXzqhs() {
        return xzqhs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.XZQHS
     *
     * @param xzqhs the value for ws_ajjbxxb.XZQHS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setXzqhs(String xzqhs) {
        this.xzqhs = xzqhs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.LAND
     *
     * @return the value of ws_ajjbxxb.LAND
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getLand() {
        return land;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.LAND
     *
     * @param land the value for ws_ajjbxxb.LAND
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setLand(String land) {
        this.land = land;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.TCGXQYY
     *
     * @return the value of ws_ajjbxxb.TCGXQYY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getTcgxqyy() {
        return tcgxqyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.TCGXQYY
     *
     * @param tcgxqyy the value for ws_ajjbxxb.TCGXQYY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setTcgxqyy(String tcgxqyy) {
        this.tcgxqyy = tcgxqyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.JAFS
     *
     * @return the value of ws_ajjbxxb.JAFS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getJafs() {
        return jafs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.JAFS
     *
     * @param jafs the value for ws_ajjbxxb.JAFS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setJafs(String jafs) {
        this.jafs = jafs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.PJSJ
     *
     * @return the value of ws_ajjbxxb.PJSJ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getPjsj() {
        return pjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.PJSJ
     *
     * @param pjsj the value for ws_ajjbxxb.PJSJ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setPjsj(String pjsj) {
        this.pjsj = pjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.JAND
     *
     * @return the value of ws_ajjbxxb.JAND
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getJand() {
        return jand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.JAND
     *
     * @param jand the value for ws_ajjbxxb.JAND
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setJand(String jand) {
        this.jand = jand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.JAYF
     *
     * @return the value of ws_ajjbxxb.JAYF
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getJayf() {
        return jayf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.JAYF
     *
     * @param jayf the value for ws_ajjbxxb.JAYF
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setJayf(String jayf) {
        this.jayf = jayf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.KSSZ
     *
     * @return the value of ws_ajjbxxb.KSSZ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getKssz() {
        return kssz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.KSSZ
     *
     * @param kssz the value for ws_ajjbxxb.KSSZ
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setKssz(String kssz) {
        this.kssz = kssz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.SSQX
     *
     * @return the value of ws_ajjbxxb.SSQX
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getSsqx() {
        return ssqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.SSQX
     *
     * @param ssqx the value for ws_ajjbxxb.SSQX
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setSsqx(String ssqx) {
        this.ssqx = ssqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.SSTJCL
     *
     * @return the value of ws_ajjbxxb.SSTJCL
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getSstjcl() {
        return sstjcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.SSTJCL
     *
     * @param sstjcl the value for ws_ajjbxxb.SSTJCL
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setSstjcl(String sstjcl) {
        this.sstjcl = sstjcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.SFFHCS
     *
     * @return the value of ws_ajjbxxb.SFFHCS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getSffhcs() {
        return sffhcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.SFFHCS
     *
     * @param sffhcs the value for ws_ajjbxxb.SFFHCS
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setSffhcs(String sffhcs) {
        this.sffhcs = sffhcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.FHCSYY
     *
     * @return the value of ws_ajjbxxb.FHCSYY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getFhcsyy() {
        return fhcsyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.FHCSYY
     *
     * @param fhcsyy the value for ws_ajjbxxb.FHCSYY
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setFhcsyy(String fhcsyy) {
        this.fhcsyy = fhcsyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_ajjbxxb.JAZBD
     *
     * @return the value of ws_ajjbxxb.JAZBD
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public String getJazbd() {
        return jazbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_ajjbxxb.JAZBD
     *
     * @param jazbd the value for ws_ajjbxxb.JAZBD
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    public void setJazbd(String jazbd) {
        this.jazbd = jazbd;
    }
}