package main.java.generator.po;

public class WsDsrQzcsPo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.AJXH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private Integer ajxh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.QKBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private Integer qkbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.DSRBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private Integer dsrbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.QKLB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String qklb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.CFTIME
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String cftime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.CFYY
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String cfyy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.SFDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String sfdw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.CFXS
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String cfxs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.CFRQ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String cfrq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsr_qk.XMSFSJ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xmsfsj;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.AJXH
	 * @return  the value of ws_dsr_qk.AJXH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public Integer getAjxh() {
		return ajxh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.AJXH
	 * @param ajxh  the value for ws_dsr_qk.AJXH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setAjxh(Integer ajxh) {
		this.ajxh = ajxh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.QKBH
	 * @return  the value of ws_dsr_qk.QKBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public Integer getQkbh() {
		return qkbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.QKBH
	 * @param qkbh  the value for ws_dsr_qk.QKBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setQkbh(Integer qkbh) {
		this.qkbh = qkbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.DSRBH
	 * @return  the value of ws_dsr_qk.DSRBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public Integer getDsrbh() {
		return dsrbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.DSRBH
	 * @param dsrbh  the value for ws_dsr_qk.DSRBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setDsrbh(Integer dsrbh) {
		this.dsrbh = dsrbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.QKLB
	 * @return  the value of ws_dsr_qk.QKLB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getQklb() {
		return qklb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.QKLB
	 * @param qklb  the value for ws_dsr_qk.QKLB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setQklb(String qklb) {
		this.qklb = qklb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.CFTIME
	 * @return  the value of ws_dsr_qk.CFTIME
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getCftime() {
		return cftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.CFTIME
	 * @param cftime  the value for ws_dsr_qk.CFTIME
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setCftime(String cftime) {
		this.cftime = cftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.CFYY
	 * @return  the value of ws_dsr_qk.CFYY
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getCfyy() {
		return cfyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.CFYY
	 * @param cfyy  the value for ws_dsr_qk.CFYY
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setCfyy(String cfyy) {
		this.cfyy = cfyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.SFDW
	 * @return  the value of ws_dsr_qk.SFDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getSfdw() {
		return sfdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.SFDW
	 * @param sfdw  the value for ws_dsr_qk.SFDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setSfdw(String sfdw) {
		this.sfdw = sfdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.CFXS
	 * @return  the value of ws_dsr_qk.CFXS
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getCfxs() {
		return cfxs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.CFXS
	 * @param cfxs  the value for ws_dsr_qk.CFXS
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setCfxs(String cfxs) {
		this.cfxs = cfxs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.CFRQ
	 * @return  the value of ws_dsr_qk.CFRQ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getCfrq() {
		return cfrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.CFRQ
	 * @param cfrq  the value for ws_dsr_qk.CFRQ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setCfrq(String cfrq) {
		this.cfrq = cfrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsr_qk.XMSFSJ
	 * @return  the value of ws_dsr_qk.XMSFSJ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXmsfsj() {
		return xmsfsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsr_qk.XMSFSJ
	 * @param xmsfsj  the value for ws_dsr_qk.XMSFSJ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXmsfsj(String xmsfsj) {
		this.xmsfsj = xmsfsj;
	}
}