package main.java.generator.po;

public class WsDsrbPo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.AJXH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private Integer ajxh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.DSRBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private Integer dsrbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.SSDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String ssdw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.YSSSDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String ysssdw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.DSRLB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String dsrlb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.XM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.XB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.MZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String mz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.GJ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String gj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.WHCD
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String whcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.ZJLX
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String zjlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.ZJHM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String zjhm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.ZW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String zw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.DZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String dz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.SFZH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String sfzh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.TSHY
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String tshy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.JGDBR
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String jgdbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.DWXZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String dwxz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.XZFLGXZT
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xzflgxzt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.XZGLFW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xzglfw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.BGLX
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String bglx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.ZZJGDM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String zzjgdm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.SFBHR
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String sfbhr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.ZRRSF
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String zrrsf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.HJSZD
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String hjszd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.XJYCS
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xjycs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.XSZRNL
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xszrnl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.SFCT
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String sfct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.XW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String xw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ws_dsrb.ZZMM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	private String zzmm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.AJXH
	 * @return  the value of ws_dsrb.AJXH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public Integer getAjxh() {
		return ajxh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.AJXH
	 * @param ajxh  the value for ws_dsrb.AJXH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setAjxh(Integer ajxh) {
		this.ajxh = ajxh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.DSRBH
	 * @return  the value of ws_dsrb.DSRBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public Integer getDsrbh() {
		return dsrbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.DSRBH
	 * @param dsrbh  the value for ws_dsrb.DSRBH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setDsrbh(Integer dsrbh) {
		this.dsrbh = dsrbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.SSDW
	 * @return  the value of ws_dsrb.SSDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getSsdw() {
		return ssdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.SSDW
	 * @param ssdw  the value for ws_dsrb.SSDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setSsdw(String ssdw) {
		this.ssdw = ssdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.YSSSDW
	 * @return  the value of ws_dsrb.YSSSDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getYsssdw() {
		return ysssdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.YSSSDW
	 * @param ysssdw  the value for ws_dsrb.YSSSDW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setYsssdw(String ysssdw) {
		this.ysssdw = ysssdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.DSRLB
	 * @return  the value of ws_dsrb.DSRLB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getDsrlb() {
		return dsrlb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.DSRLB
	 * @param dsrlb  the value for ws_dsrb.DSRLB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setDsrlb(String dsrlb) {
		this.dsrlb = dsrlb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.XM
	 * @return  the value of ws_dsrb.XM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXm() {
		return xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.XM
	 * @param xm  the value for ws_dsrb.XM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXm(String xm) {
		this.xm = xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.XB
	 * @return  the value of ws_dsrb.XB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXb() {
		return xb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.XB
	 * @param xb  the value for ws_dsrb.XB
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXb(String xb) {
		this.xb = xb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.MZ
	 * @return  the value of ws_dsrb.MZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getMz() {
		return mz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.MZ
	 * @param mz  the value for ws_dsrb.MZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setMz(String mz) {
		this.mz = mz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.GJ
	 * @return  the value of ws_dsrb.GJ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getGj() {
		return gj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.GJ
	 * @param gj  the value for ws_dsrb.GJ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setGj(String gj) {
		this.gj = gj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.WHCD
	 * @return  the value of ws_dsrb.WHCD
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getWhcd() {
		return whcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.WHCD
	 * @param whcd  the value for ws_dsrb.WHCD
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setWhcd(String whcd) {
		this.whcd = whcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.ZJLX
	 * @return  the value of ws_dsrb.ZJLX
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getZjlx() {
		return zjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.ZJLX
	 * @param zjlx  the value for ws_dsrb.ZJLX
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setZjlx(String zjlx) {
		this.zjlx = zjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.ZJHM
	 * @return  the value of ws_dsrb.ZJHM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getZjhm() {
		return zjhm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.ZJHM
	 * @param zjhm  the value for ws_dsrb.ZJHM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setZjhm(String zjhm) {
		this.zjhm = zjhm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.ZW
	 * @return  the value of ws_dsrb.ZW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getZw() {
		return zw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.ZW
	 * @param zw  the value for ws_dsrb.ZW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setZw(String zw) {
		this.zw = zw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.DZ
	 * @return  the value of ws_dsrb.DZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getDz() {
		return dz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.DZ
	 * @param dz  the value for ws_dsrb.DZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setDz(String dz) {
		this.dz = dz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.SFZH
	 * @return  the value of ws_dsrb.SFZH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getSfzh() {
		return sfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.SFZH
	 * @param sfzh  the value for ws_dsrb.SFZH
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.TSHY
	 * @return  the value of ws_dsrb.TSHY
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getTshy() {
		return tshy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.TSHY
	 * @param tshy  the value for ws_dsrb.TSHY
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setTshy(String tshy) {
		this.tshy = tshy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.JGDBR
	 * @return  the value of ws_dsrb.JGDBR
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getJgdbr() {
		return jgdbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.JGDBR
	 * @param jgdbr  the value for ws_dsrb.JGDBR
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setJgdbr(String jgdbr) {
		this.jgdbr = jgdbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.DWXZ
	 * @return  the value of ws_dsrb.DWXZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getDwxz() {
		return dwxz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.DWXZ
	 * @param dwxz  the value for ws_dsrb.DWXZ
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setDwxz(String dwxz) {
		this.dwxz = dwxz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.XZFLGXZT
	 * @return  the value of ws_dsrb.XZFLGXZT
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXzflgxzt() {
		return xzflgxzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.XZFLGXZT
	 * @param xzflgxzt  the value for ws_dsrb.XZFLGXZT
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXzflgxzt(String xzflgxzt) {
		this.xzflgxzt = xzflgxzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.XZGLFW
	 * @return  the value of ws_dsrb.XZGLFW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXzglfw() {
		return xzglfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.XZGLFW
	 * @param xzglfw  the value for ws_dsrb.XZGLFW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXzglfw(String xzglfw) {
		this.xzglfw = xzglfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.BGLX
	 * @return  the value of ws_dsrb.BGLX
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getBglx() {
		return bglx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.BGLX
	 * @param bglx  the value for ws_dsrb.BGLX
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setBglx(String bglx) {
		this.bglx = bglx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.ZZJGDM
	 * @return  the value of ws_dsrb.ZZJGDM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getZzjgdm() {
		return zzjgdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.ZZJGDM
	 * @param zzjgdm  the value for ws_dsrb.ZZJGDM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setZzjgdm(String zzjgdm) {
		this.zzjgdm = zzjgdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.SFBHR
	 * @return  the value of ws_dsrb.SFBHR
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getSfbhr() {
		return sfbhr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.SFBHR
	 * @param sfbhr  the value for ws_dsrb.SFBHR
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setSfbhr(String sfbhr) {
		this.sfbhr = sfbhr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.ZRRSF
	 * @return  the value of ws_dsrb.ZRRSF
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getZrrsf() {
		return zrrsf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.ZRRSF
	 * @param zrrsf  the value for ws_dsrb.ZRRSF
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setZrrsf(String zrrsf) {
		this.zrrsf = zrrsf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.HJSZD
	 * @return  the value of ws_dsrb.HJSZD
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getHjszd() {
		return hjszd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.HJSZD
	 * @param hjszd  the value for ws_dsrb.HJSZD
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setHjszd(String hjszd) {
		this.hjszd = hjszd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.XJYCS
	 * @return  the value of ws_dsrb.XJYCS
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXjycs() {
		return xjycs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.XJYCS
	 * @param xjycs  the value for ws_dsrb.XJYCS
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXjycs(String xjycs) {
		this.xjycs = xjycs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.XSZRNL
	 * @return  the value of ws_dsrb.XSZRNL
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXszrnl() {
		return xszrnl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.XSZRNL
	 * @param xszrnl  the value for ws_dsrb.XSZRNL
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXszrnl(String xszrnl) {
		this.xszrnl = xszrnl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.SFCT
	 * @return  the value of ws_dsrb.SFCT
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getSfct() {
		return sfct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.SFCT
	 * @param sfct  the value for ws_dsrb.SFCT
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setSfct(String sfct) {
		this.sfct = sfct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.XW
	 * @return  the value of ws_dsrb.XW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getXw() {
		return xw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.XW
	 * @param xw  the value for ws_dsrb.XW
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setXw(String xw) {
		this.xw = xw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ws_dsrb.ZZMM
	 * @return  the value of ws_dsrb.ZZMM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public String getZzmm() {
		return zzmm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ws_dsrb.ZZMM
	 * @param zzmm  the value for ws_dsrb.ZZMM
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	public void setZzmm(String zzmm) {
		this.zzmm = zzmm;
	}
}