package main.java.generator.po;

import java.util.ArrayList;
import java.util.List;

public class WsDsrbPoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public WsDsrbPoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAjxhIsNull() {
			addCriterion("AJXH is null");
			return (Criteria) this;
		}

		public Criteria andAjxhIsNotNull() {
			addCriterion("AJXH is not null");
			return (Criteria) this;
		}

		public Criteria andAjxhEqualTo(Integer value) {
			addCriterion("AJXH =", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhNotEqualTo(Integer value) {
			addCriterion("AJXH <>", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhGreaterThan(Integer value) {
			addCriterion("AJXH >", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhGreaterThanOrEqualTo(Integer value) {
			addCriterion("AJXH >=", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhLessThan(Integer value) {
			addCriterion("AJXH <", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhLessThanOrEqualTo(Integer value) {
			addCriterion("AJXH <=", value, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhIn(List<Integer> values) {
			addCriterion("AJXH in", values, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhNotIn(List<Integer> values) {
			addCriterion("AJXH not in", values, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhBetween(Integer value1, Integer value2) {
			addCriterion("AJXH between", value1, value2, "ajxh");
			return (Criteria) this;
		}

		public Criteria andAjxhNotBetween(Integer value1, Integer value2) {
			addCriterion("AJXH not between", value1, value2, "ajxh");
			return (Criteria) this;
		}

		public Criteria andDsrbhIsNull() {
			addCriterion("DSRBH is null");
			return (Criteria) this;
		}

		public Criteria andDsrbhIsNotNull() {
			addCriterion("DSRBH is not null");
			return (Criteria) this;
		}

		public Criteria andDsrbhEqualTo(Integer value) {
			addCriterion("DSRBH =", value, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhNotEqualTo(Integer value) {
			addCriterion("DSRBH <>", value, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhGreaterThan(Integer value) {
			addCriterion("DSRBH >", value, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhGreaterThanOrEqualTo(Integer value) {
			addCriterion("DSRBH >=", value, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhLessThan(Integer value) {
			addCriterion("DSRBH <", value, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhLessThanOrEqualTo(Integer value) {
			addCriterion("DSRBH <=", value, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhIn(List<Integer> values) {
			addCriterion("DSRBH in", values, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhNotIn(List<Integer> values) {
			addCriterion("DSRBH not in", values, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhBetween(Integer value1, Integer value2) {
			addCriterion("DSRBH between", value1, value2, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andDsrbhNotBetween(Integer value1, Integer value2) {
			addCriterion("DSRBH not between", value1, value2, "dsrbh");
			return (Criteria) this;
		}

		public Criteria andSsdwIsNull() {
			addCriterion("SSDW is null");
			return (Criteria) this;
		}

		public Criteria andSsdwIsNotNull() {
			addCriterion("SSDW is not null");
			return (Criteria) this;
		}

		public Criteria andSsdwEqualTo(String value) {
			addCriterion("SSDW =", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwNotEqualTo(String value) {
			addCriterion("SSDW <>", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwGreaterThan(String value) {
			addCriterion("SSDW >", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwGreaterThanOrEqualTo(String value) {
			addCriterion("SSDW >=", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwLessThan(String value) {
			addCriterion("SSDW <", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwLessThanOrEqualTo(String value) {
			addCriterion("SSDW <=", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwLike(String value) {
			addCriterion("SSDW like", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwNotLike(String value) {
			addCriterion("SSDW not like", value, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwIn(List<String> values) {
			addCriterion("SSDW in", values, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwNotIn(List<String> values) {
			addCriterion("SSDW not in", values, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwBetween(String value1, String value2) {
			addCriterion("SSDW between", value1, value2, "ssdw");
			return (Criteria) this;
		}

		public Criteria andSsdwNotBetween(String value1, String value2) {
			addCriterion("SSDW not between", value1, value2, "ssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwIsNull() {
			addCriterion("YSSSDW is null");
			return (Criteria) this;
		}

		public Criteria andYsssdwIsNotNull() {
			addCriterion("YSSSDW is not null");
			return (Criteria) this;
		}

		public Criteria andYsssdwEqualTo(String value) {
			addCriterion("YSSSDW =", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwNotEqualTo(String value) {
			addCriterion("YSSSDW <>", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwGreaterThan(String value) {
			addCriterion("YSSSDW >", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwGreaterThanOrEqualTo(String value) {
			addCriterion("YSSSDW >=", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwLessThan(String value) {
			addCriterion("YSSSDW <", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwLessThanOrEqualTo(String value) {
			addCriterion("YSSSDW <=", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwLike(String value) {
			addCriterion("YSSSDW like", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwNotLike(String value) {
			addCriterion("YSSSDW not like", value, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwIn(List<String> values) {
			addCriterion("YSSSDW in", values, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwNotIn(List<String> values) {
			addCriterion("YSSSDW not in", values, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwBetween(String value1, String value2) {
			addCriterion("YSSSDW between", value1, value2, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andYsssdwNotBetween(String value1, String value2) {
			addCriterion("YSSSDW not between", value1, value2, "ysssdw");
			return (Criteria) this;
		}

		public Criteria andDsrlbIsNull() {
			addCriterion("DSRLB is null");
			return (Criteria) this;
		}

		public Criteria andDsrlbIsNotNull() {
			addCriterion("DSRLB is not null");
			return (Criteria) this;
		}

		public Criteria andDsrlbEqualTo(String value) {
			addCriterion("DSRLB =", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbNotEqualTo(String value) {
			addCriterion("DSRLB <>", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbGreaterThan(String value) {
			addCriterion("DSRLB >", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbGreaterThanOrEqualTo(String value) {
			addCriterion("DSRLB >=", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbLessThan(String value) {
			addCriterion("DSRLB <", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbLessThanOrEqualTo(String value) {
			addCriterion("DSRLB <=", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbLike(String value) {
			addCriterion("DSRLB like", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbNotLike(String value) {
			addCriterion("DSRLB not like", value, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbIn(List<String> values) {
			addCriterion("DSRLB in", values, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbNotIn(List<String> values) {
			addCriterion("DSRLB not in", values, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbBetween(String value1, String value2) {
			addCriterion("DSRLB between", value1, value2, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andDsrlbNotBetween(String value1, String value2) {
			addCriterion("DSRLB not between", value1, value2, "dsrlb");
			return (Criteria) this;
		}

		public Criteria andXmIsNull() {
			addCriterion("XM is null");
			return (Criteria) this;
		}

		public Criteria andXmIsNotNull() {
			addCriterion("XM is not null");
			return (Criteria) this;
		}

		public Criteria andXmEqualTo(String value) {
			addCriterion("XM =", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmNotEqualTo(String value) {
			addCriterion("XM <>", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmGreaterThan(String value) {
			addCriterion("XM >", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmGreaterThanOrEqualTo(String value) {
			addCriterion("XM >=", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmLessThan(String value) {
			addCriterion("XM <", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmLessThanOrEqualTo(String value) {
			addCriterion("XM <=", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmLike(String value) {
			addCriterion("XM like", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmNotLike(String value) {
			addCriterion("XM not like", value, "xm");
			return (Criteria) this;
		}

		public Criteria andXmIn(List<String> values) {
			addCriterion("XM in", values, "xm");
			return (Criteria) this;
		}

		public Criteria andXmNotIn(List<String> values) {
			addCriterion("XM not in", values, "xm");
			return (Criteria) this;
		}

		public Criteria andXmBetween(String value1, String value2) {
			addCriterion("XM between", value1, value2, "xm");
			return (Criteria) this;
		}

		public Criteria andXmNotBetween(String value1, String value2) {
			addCriterion("XM not between", value1, value2, "xm");
			return (Criteria) this;
		}

		public Criteria andXbIsNull() {
			addCriterion("XB is null");
			return (Criteria) this;
		}

		public Criteria andXbIsNotNull() {
			addCriterion("XB is not null");
			return (Criteria) this;
		}

		public Criteria andXbEqualTo(String value) {
			addCriterion("XB =", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbNotEqualTo(String value) {
			addCriterion("XB <>", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbGreaterThan(String value) {
			addCriterion("XB >", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbGreaterThanOrEqualTo(String value) {
			addCriterion("XB >=", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbLessThan(String value) {
			addCriterion("XB <", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbLessThanOrEqualTo(String value) {
			addCriterion("XB <=", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbLike(String value) {
			addCriterion("XB like", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbNotLike(String value) {
			addCriterion("XB not like", value, "xb");
			return (Criteria) this;
		}

		public Criteria andXbIn(List<String> values) {
			addCriterion("XB in", values, "xb");
			return (Criteria) this;
		}

		public Criteria andXbNotIn(List<String> values) {
			addCriterion("XB not in", values, "xb");
			return (Criteria) this;
		}

		public Criteria andXbBetween(String value1, String value2) {
			addCriterion("XB between", value1, value2, "xb");
			return (Criteria) this;
		}

		public Criteria andXbNotBetween(String value1, String value2) {
			addCriterion("XB not between", value1, value2, "xb");
			return (Criteria) this;
		}

		public Criteria andMzIsNull() {
			addCriterion("MZ is null");
			return (Criteria) this;
		}

		public Criteria andMzIsNotNull() {
			addCriterion("MZ is not null");
			return (Criteria) this;
		}

		public Criteria andMzEqualTo(String value) {
			addCriterion("MZ =", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzNotEqualTo(String value) {
			addCriterion("MZ <>", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzGreaterThan(String value) {
			addCriterion("MZ >", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzGreaterThanOrEqualTo(String value) {
			addCriterion("MZ >=", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzLessThan(String value) {
			addCriterion("MZ <", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzLessThanOrEqualTo(String value) {
			addCriterion("MZ <=", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzLike(String value) {
			addCriterion("MZ like", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzNotLike(String value) {
			addCriterion("MZ not like", value, "mz");
			return (Criteria) this;
		}

		public Criteria andMzIn(List<String> values) {
			addCriterion("MZ in", values, "mz");
			return (Criteria) this;
		}

		public Criteria andMzNotIn(List<String> values) {
			addCriterion("MZ not in", values, "mz");
			return (Criteria) this;
		}

		public Criteria andMzBetween(String value1, String value2) {
			addCriterion("MZ between", value1, value2, "mz");
			return (Criteria) this;
		}

		public Criteria andMzNotBetween(String value1, String value2) {
			addCriterion("MZ not between", value1, value2, "mz");
			return (Criteria) this;
		}

		public Criteria andGjIsNull() {
			addCriterion("GJ is null");
			return (Criteria) this;
		}

		public Criteria andGjIsNotNull() {
			addCriterion("GJ is not null");
			return (Criteria) this;
		}

		public Criteria andGjEqualTo(String value) {
			addCriterion("GJ =", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjNotEqualTo(String value) {
			addCriterion("GJ <>", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjGreaterThan(String value) {
			addCriterion("GJ >", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjGreaterThanOrEqualTo(String value) {
			addCriterion("GJ >=", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjLessThan(String value) {
			addCriterion("GJ <", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjLessThanOrEqualTo(String value) {
			addCriterion("GJ <=", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjLike(String value) {
			addCriterion("GJ like", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjNotLike(String value) {
			addCriterion("GJ not like", value, "gj");
			return (Criteria) this;
		}

		public Criteria andGjIn(List<String> values) {
			addCriterion("GJ in", values, "gj");
			return (Criteria) this;
		}

		public Criteria andGjNotIn(List<String> values) {
			addCriterion("GJ not in", values, "gj");
			return (Criteria) this;
		}

		public Criteria andGjBetween(String value1, String value2) {
			addCriterion("GJ between", value1, value2, "gj");
			return (Criteria) this;
		}

		public Criteria andGjNotBetween(String value1, String value2) {
			addCriterion("GJ not between", value1, value2, "gj");
			return (Criteria) this;
		}

		public Criteria andWhcdIsNull() {
			addCriterion("WHCD is null");
			return (Criteria) this;
		}

		public Criteria andWhcdIsNotNull() {
			addCriterion("WHCD is not null");
			return (Criteria) this;
		}

		public Criteria andWhcdEqualTo(String value) {
			addCriterion("WHCD =", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdNotEqualTo(String value) {
			addCriterion("WHCD <>", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdGreaterThan(String value) {
			addCriterion("WHCD >", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdGreaterThanOrEqualTo(String value) {
			addCriterion("WHCD >=", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdLessThan(String value) {
			addCriterion("WHCD <", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdLessThanOrEqualTo(String value) {
			addCriterion("WHCD <=", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdLike(String value) {
			addCriterion("WHCD like", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdNotLike(String value) {
			addCriterion("WHCD not like", value, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdIn(List<String> values) {
			addCriterion("WHCD in", values, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdNotIn(List<String> values) {
			addCriterion("WHCD not in", values, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdBetween(String value1, String value2) {
			addCriterion("WHCD between", value1, value2, "whcd");
			return (Criteria) this;
		}

		public Criteria andWhcdNotBetween(String value1, String value2) {
			addCriterion("WHCD not between", value1, value2, "whcd");
			return (Criteria) this;
		}

		public Criteria andZjlxIsNull() {
			addCriterion("ZJLX is null");
			return (Criteria) this;
		}

		public Criteria andZjlxIsNotNull() {
			addCriterion("ZJLX is not null");
			return (Criteria) this;
		}

		public Criteria andZjlxEqualTo(String value) {
			addCriterion("ZJLX =", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxNotEqualTo(String value) {
			addCriterion("ZJLX <>", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxGreaterThan(String value) {
			addCriterion("ZJLX >", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxGreaterThanOrEqualTo(String value) {
			addCriterion("ZJLX >=", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxLessThan(String value) {
			addCriterion("ZJLX <", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxLessThanOrEqualTo(String value) {
			addCriterion("ZJLX <=", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxLike(String value) {
			addCriterion("ZJLX like", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxNotLike(String value) {
			addCriterion("ZJLX not like", value, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxIn(List<String> values) {
			addCriterion("ZJLX in", values, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxNotIn(List<String> values) {
			addCriterion("ZJLX not in", values, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxBetween(String value1, String value2) {
			addCriterion("ZJLX between", value1, value2, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjlxNotBetween(String value1, String value2) {
			addCriterion("ZJLX not between", value1, value2, "zjlx");
			return (Criteria) this;
		}

		public Criteria andZjhmIsNull() {
			addCriterion("ZJHM is null");
			return (Criteria) this;
		}

		public Criteria andZjhmIsNotNull() {
			addCriterion("ZJHM is not null");
			return (Criteria) this;
		}

		public Criteria andZjhmEqualTo(String value) {
			addCriterion("ZJHM =", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmNotEqualTo(String value) {
			addCriterion("ZJHM <>", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmGreaterThan(String value) {
			addCriterion("ZJHM >", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmGreaterThanOrEqualTo(String value) {
			addCriterion("ZJHM >=", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmLessThan(String value) {
			addCriterion("ZJHM <", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmLessThanOrEqualTo(String value) {
			addCriterion("ZJHM <=", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmLike(String value) {
			addCriterion("ZJHM like", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmNotLike(String value) {
			addCriterion("ZJHM not like", value, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmIn(List<String> values) {
			addCriterion("ZJHM in", values, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmNotIn(List<String> values) {
			addCriterion("ZJHM not in", values, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmBetween(String value1, String value2) {
			addCriterion("ZJHM between", value1, value2, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZjhmNotBetween(String value1, String value2) {
			addCriterion("ZJHM not between", value1, value2, "zjhm");
			return (Criteria) this;
		}

		public Criteria andZwIsNull() {
			addCriterion("ZW is null");
			return (Criteria) this;
		}

		public Criteria andZwIsNotNull() {
			addCriterion("ZW is not null");
			return (Criteria) this;
		}

		public Criteria andZwEqualTo(String value) {
			addCriterion("ZW =", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwNotEqualTo(String value) {
			addCriterion("ZW <>", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwGreaterThan(String value) {
			addCriterion("ZW >", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwGreaterThanOrEqualTo(String value) {
			addCriterion("ZW >=", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwLessThan(String value) {
			addCriterion("ZW <", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwLessThanOrEqualTo(String value) {
			addCriterion("ZW <=", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwLike(String value) {
			addCriterion("ZW like", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwNotLike(String value) {
			addCriterion("ZW not like", value, "zw");
			return (Criteria) this;
		}

		public Criteria andZwIn(List<String> values) {
			addCriterion("ZW in", values, "zw");
			return (Criteria) this;
		}

		public Criteria andZwNotIn(List<String> values) {
			addCriterion("ZW not in", values, "zw");
			return (Criteria) this;
		}

		public Criteria andZwBetween(String value1, String value2) {
			addCriterion("ZW between", value1, value2, "zw");
			return (Criteria) this;
		}

		public Criteria andZwNotBetween(String value1, String value2) {
			addCriterion("ZW not between", value1, value2, "zw");
			return (Criteria) this;
		}

		public Criteria andDzIsNull() {
			addCriterion("DZ is null");
			return (Criteria) this;
		}

		public Criteria andDzIsNotNull() {
			addCriterion("DZ is not null");
			return (Criteria) this;
		}

		public Criteria andDzEqualTo(String value) {
			addCriterion("DZ =", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzNotEqualTo(String value) {
			addCriterion("DZ <>", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzGreaterThan(String value) {
			addCriterion("DZ >", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzGreaterThanOrEqualTo(String value) {
			addCriterion("DZ >=", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzLessThan(String value) {
			addCriterion("DZ <", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzLessThanOrEqualTo(String value) {
			addCriterion("DZ <=", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzLike(String value) {
			addCriterion("DZ like", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzNotLike(String value) {
			addCriterion("DZ not like", value, "dz");
			return (Criteria) this;
		}

		public Criteria andDzIn(List<String> values) {
			addCriterion("DZ in", values, "dz");
			return (Criteria) this;
		}

		public Criteria andDzNotIn(List<String> values) {
			addCriterion("DZ not in", values, "dz");
			return (Criteria) this;
		}

		public Criteria andDzBetween(String value1, String value2) {
			addCriterion("DZ between", value1, value2, "dz");
			return (Criteria) this;
		}

		public Criteria andDzNotBetween(String value1, String value2) {
			addCriterion("DZ not between", value1, value2, "dz");
			return (Criteria) this;
		}

		public Criteria andSfzhIsNull() {
			addCriterion("SFZH is null");
			return (Criteria) this;
		}

		public Criteria andSfzhIsNotNull() {
			addCriterion("SFZH is not null");
			return (Criteria) this;
		}

		public Criteria andSfzhEqualTo(String value) {
			addCriterion("SFZH =", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhNotEqualTo(String value) {
			addCriterion("SFZH <>", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhGreaterThan(String value) {
			addCriterion("SFZH >", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhGreaterThanOrEqualTo(String value) {
			addCriterion("SFZH >=", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhLessThan(String value) {
			addCriterion("SFZH <", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhLessThanOrEqualTo(String value) {
			addCriterion("SFZH <=", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhLike(String value) {
			addCriterion("SFZH like", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhNotLike(String value) {
			addCriterion("SFZH not like", value, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhIn(List<String> values) {
			addCriterion("SFZH in", values, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhNotIn(List<String> values) {
			addCriterion("SFZH not in", values, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhBetween(String value1, String value2) {
			addCriterion("SFZH between", value1, value2, "sfzh");
			return (Criteria) this;
		}

		public Criteria andSfzhNotBetween(String value1, String value2) {
			addCriterion("SFZH not between", value1, value2, "sfzh");
			return (Criteria) this;
		}

		public Criteria andTshyIsNull() {
			addCriterion("TSHY is null");
			return (Criteria) this;
		}

		public Criteria andTshyIsNotNull() {
			addCriterion("TSHY is not null");
			return (Criteria) this;
		}

		public Criteria andTshyEqualTo(String value) {
			addCriterion("TSHY =", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyNotEqualTo(String value) {
			addCriterion("TSHY <>", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyGreaterThan(String value) {
			addCriterion("TSHY >", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyGreaterThanOrEqualTo(String value) {
			addCriterion("TSHY >=", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyLessThan(String value) {
			addCriterion("TSHY <", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyLessThanOrEqualTo(String value) {
			addCriterion("TSHY <=", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyLike(String value) {
			addCriterion("TSHY like", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyNotLike(String value) {
			addCriterion("TSHY not like", value, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyIn(List<String> values) {
			addCriterion("TSHY in", values, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyNotIn(List<String> values) {
			addCriterion("TSHY not in", values, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyBetween(String value1, String value2) {
			addCriterion("TSHY between", value1, value2, "tshy");
			return (Criteria) this;
		}

		public Criteria andTshyNotBetween(String value1, String value2) {
			addCriterion("TSHY not between", value1, value2, "tshy");
			return (Criteria) this;
		}

		public Criteria andJgdbrIsNull() {
			addCriterion("JGDBR is null");
			return (Criteria) this;
		}

		public Criteria andJgdbrIsNotNull() {
			addCriterion("JGDBR is not null");
			return (Criteria) this;
		}

		public Criteria andJgdbrEqualTo(String value) {
			addCriterion("JGDBR =", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrNotEqualTo(String value) {
			addCriterion("JGDBR <>", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrGreaterThan(String value) {
			addCriterion("JGDBR >", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrGreaterThanOrEqualTo(String value) {
			addCriterion("JGDBR >=", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrLessThan(String value) {
			addCriterion("JGDBR <", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrLessThanOrEqualTo(String value) {
			addCriterion("JGDBR <=", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrLike(String value) {
			addCriterion("JGDBR like", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrNotLike(String value) {
			addCriterion("JGDBR not like", value, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrIn(List<String> values) {
			addCriterion("JGDBR in", values, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrNotIn(List<String> values) {
			addCriterion("JGDBR not in", values, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrBetween(String value1, String value2) {
			addCriterion("JGDBR between", value1, value2, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andJgdbrNotBetween(String value1, String value2) {
			addCriterion("JGDBR not between", value1, value2, "jgdbr");
			return (Criteria) this;
		}

		public Criteria andDwxzIsNull() {
			addCriterion("DWXZ is null");
			return (Criteria) this;
		}

		public Criteria andDwxzIsNotNull() {
			addCriterion("DWXZ is not null");
			return (Criteria) this;
		}

		public Criteria andDwxzEqualTo(String value) {
			addCriterion("DWXZ =", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzNotEqualTo(String value) {
			addCriterion("DWXZ <>", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzGreaterThan(String value) {
			addCriterion("DWXZ >", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzGreaterThanOrEqualTo(String value) {
			addCriterion("DWXZ >=", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzLessThan(String value) {
			addCriterion("DWXZ <", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzLessThanOrEqualTo(String value) {
			addCriterion("DWXZ <=", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzLike(String value) {
			addCriterion("DWXZ like", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzNotLike(String value) {
			addCriterion("DWXZ not like", value, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzIn(List<String> values) {
			addCriterion("DWXZ in", values, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzNotIn(List<String> values) {
			addCriterion("DWXZ not in", values, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzBetween(String value1, String value2) {
			addCriterion("DWXZ between", value1, value2, "dwxz");
			return (Criteria) this;
		}

		public Criteria andDwxzNotBetween(String value1, String value2) {
			addCriterion("DWXZ not between", value1, value2, "dwxz");
			return (Criteria) this;
		}

		public Criteria andXzflgxztIsNull() {
			addCriterion("XZFLGXZT is null");
			return (Criteria) this;
		}

		public Criteria andXzflgxztIsNotNull() {
			addCriterion("XZFLGXZT is not null");
			return (Criteria) this;
		}

		public Criteria andXzflgxztEqualTo(String value) {
			addCriterion("XZFLGXZT =", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztNotEqualTo(String value) {
			addCriterion("XZFLGXZT <>", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztGreaterThan(String value) {
			addCriterion("XZFLGXZT >", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztGreaterThanOrEqualTo(String value) {
			addCriterion("XZFLGXZT >=", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztLessThan(String value) {
			addCriterion("XZFLGXZT <", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztLessThanOrEqualTo(String value) {
			addCriterion("XZFLGXZT <=", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztLike(String value) {
			addCriterion("XZFLGXZT like", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztNotLike(String value) {
			addCriterion("XZFLGXZT not like", value, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztIn(List<String> values) {
			addCriterion("XZFLGXZT in", values, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztNotIn(List<String> values) {
			addCriterion("XZFLGXZT not in", values, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztBetween(String value1, String value2) {
			addCriterion("XZFLGXZT between", value1, value2, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzflgxztNotBetween(String value1, String value2) {
			addCriterion("XZFLGXZT not between", value1, value2, "xzflgxzt");
			return (Criteria) this;
		}

		public Criteria andXzglfwIsNull() {
			addCriterion("XZGLFW is null");
			return (Criteria) this;
		}

		public Criteria andXzglfwIsNotNull() {
			addCriterion("XZGLFW is not null");
			return (Criteria) this;
		}

		public Criteria andXzglfwEqualTo(String value) {
			addCriterion("XZGLFW =", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwNotEqualTo(String value) {
			addCriterion("XZGLFW <>", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwGreaterThan(String value) {
			addCriterion("XZGLFW >", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwGreaterThanOrEqualTo(String value) {
			addCriterion("XZGLFW >=", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwLessThan(String value) {
			addCriterion("XZGLFW <", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwLessThanOrEqualTo(String value) {
			addCriterion("XZGLFW <=", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwLike(String value) {
			addCriterion("XZGLFW like", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwNotLike(String value) {
			addCriterion("XZGLFW not like", value, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwIn(List<String> values) {
			addCriterion("XZGLFW in", values, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwNotIn(List<String> values) {
			addCriterion("XZGLFW not in", values, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwBetween(String value1, String value2) {
			addCriterion("XZGLFW between", value1, value2, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andXzglfwNotBetween(String value1, String value2) {
			addCriterion("XZGLFW not between", value1, value2, "xzglfw");
			return (Criteria) this;
		}

		public Criteria andBglxIsNull() {
			addCriterion("BGLX is null");
			return (Criteria) this;
		}

		public Criteria andBglxIsNotNull() {
			addCriterion("BGLX is not null");
			return (Criteria) this;
		}

		public Criteria andBglxEqualTo(String value) {
			addCriterion("BGLX =", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxNotEqualTo(String value) {
			addCriterion("BGLX <>", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxGreaterThan(String value) {
			addCriterion("BGLX >", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxGreaterThanOrEqualTo(String value) {
			addCriterion("BGLX >=", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxLessThan(String value) {
			addCriterion("BGLX <", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxLessThanOrEqualTo(String value) {
			addCriterion("BGLX <=", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxLike(String value) {
			addCriterion("BGLX like", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxNotLike(String value) {
			addCriterion("BGLX not like", value, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxIn(List<String> values) {
			addCriterion("BGLX in", values, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxNotIn(List<String> values) {
			addCriterion("BGLX not in", values, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxBetween(String value1, String value2) {
			addCriterion("BGLX between", value1, value2, "bglx");
			return (Criteria) this;
		}

		public Criteria andBglxNotBetween(String value1, String value2) {
			addCriterion("BGLX not between", value1, value2, "bglx");
			return (Criteria) this;
		}

		public Criteria andZzjgdmIsNull() {
			addCriterion("ZZJGDM is null");
			return (Criteria) this;
		}

		public Criteria andZzjgdmIsNotNull() {
			addCriterion("ZZJGDM is not null");
			return (Criteria) this;
		}

		public Criteria andZzjgdmEqualTo(String value) {
			addCriterion("ZZJGDM =", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmNotEqualTo(String value) {
			addCriterion("ZZJGDM <>", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmGreaterThan(String value) {
			addCriterion("ZZJGDM >", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmGreaterThanOrEqualTo(String value) {
			addCriterion("ZZJGDM >=", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmLessThan(String value) {
			addCriterion("ZZJGDM <", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmLessThanOrEqualTo(String value) {
			addCriterion("ZZJGDM <=", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmLike(String value) {
			addCriterion("ZZJGDM like", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmNotLike(String value) {
			addCriterion("ZZJGDM not like", value, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmIn(List<String> values) {
			addCriterion("ZZJGDM in", values, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmNotIn(List<String> values) {
			addCriterion("ZZJGDM not in", values, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmBetween(String value1, String value2) {
			addCriterion("ZZJGDM between", value1, value2, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andZzjgdmNotBetween(String value1, String value2) {
			addCriterion("ZZJGDM not between", value1, value2, "zzjgdm");
			return (Criteria) this;
		}

		public Criteria andSfbhrIsNull() {
			addCriterion("SFBHR is null");
			return (Criteria) this;
		}

		public Criteria andSfbhrIsNotNull() {
			addCriterion("SFBHR is not null");
			return (Criteria) this;
		}

		public Criteria andSfbhrEqualTo(String value) {
			addCriterion("SFBHR =", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrNotEqualTo(String value) {
			addCriterion("SFBHR <>", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrGreaterThan(String value) {
			addCriterion("SFBHR >", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrGreaterThanOrEqualTo(String value) {
			addCriterion("SFBHR >=", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrLessThan(String value) {
			addCriterion("SFBHR <", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrLessThanOrEqualTo(String value) {
			addCriterion("SFBHR <=", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrLike(String value) {
			addCriterion("SFBHR like", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrNotLike(String value) {
			addCriterion("SFBHR not like", value, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrIn(List<String> values) {
			addCriterion("SFBHR in", values, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrNotIn(List<String> values) {
			addCriterion("SFBHR not in", values, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrBetween(String value1, String value2) {
			addCriterion("SFBHR between", value1, value2, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andSfbhrNotBetween(String value1, String value2) {
			addCriterion("SFBHR not between", value1, value2, "sfbhr");
			return (Criteria) this;
		}

		public Criteria andZrrsfIsNull() {
			addCriterion("ZRRSF is null");
			return (Criteria) this;
		}

		public Criteria andZrrsfIsNotNull() {
			addCriterion("ZRRSF is not null");
			return (Criteria) this;
		}

		public Criteria andZrrsfEqualTo(String value) {
			addCriterion("ZRRSF =", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfNotEqualTo(String value) {
			addCriterion("ZRRSF <>", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfGreaterThan(String value) {
			addCriterion("ZRRSF >", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfGreaterThanOrEqualTo(String value) {
			addCriterion("ZRRSF >=", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfLessThan(String value) {
			addCriterion("ZRRSF <", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfLessThanOrEqualTo(String value) {
			addCriterion("ZRRSF <=", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfLike(String value) {
			addCriterion("ZRRSF like", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfNotLike(String value) {
			addCriterion("ZRRSF not like", value, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfIn(List<String> values) {
			addCriterion("ZRRSF in", values, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfNotIn(List<String> values) {
			addCriterion("ZRRSF not in", values, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfBetween(String value1, String value2) {
			addCriterion("ZRRSF between", value1, value2, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andZrrsfNotBetween(String value1, String value2) {
			addCriterion("ZRRSF not between", value1, value2, "zrrsf");
			return (Criteria) this;
		}

		public Criteria andHjszdIsNull() {
			addCriterion("HJSZD is null");
			return (Criteria) this;
		}

		public Criteria andHjszdIsNotNull() {
			addCriterion("HJSZD is not null");
			return (Criteria) this;
		}

		public Criteria andHjszdEqualTo(String value) {
			addCriterion("HJSZD =", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdNotEqualTo(String value) {
			addCriterion("HJSZD <>", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdGreaterThan(String value) {
			addCriterion("HJSZD >", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdGreaterThanOrEqualTo(String value) {
			addCriterion("HJSZD >=", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdLessThan(String value) {
			addCriterion("HJSZD <", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdLessThanOrEqualTo(String value) {
			addCriterion("HJSZD <=", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdLike(String value) {
			addCriterion("HJSZD like", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdNotLike(String value) {
			addCriterion("HJSZD not like", value, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdIn(List<String> values) {
			addCriterion("HJSZD in", values, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdNotIn(List<String> values) {
			addCriterion("HJSZD not in", values, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdBetween(String value1, String value2) {
			addCriterion("HJSZD between", value1, value2, "hjszd");
			return (Criteria) this;
		}

		public Criteria andHjszdNotBetween(String value1, String value2) {
			addCriterion("HJSZD not between", value1, value2, "hjszd");
			return (Criteria) this;
		}

		public Criteria andXjycsIsNull() {
			addCriterion("XJYCS is null");
			return (Criteria) this;
		}

		public Criteria andXjycsIsNotNull() {
			addCriterion("XJYCS is not null");
			return (Criteria) this;
		}

		public Criteria andXjycsEqualTo(String value) {
			addCriterion("XJYCS =", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsNotEqualTo(String value) {
			addCriterion("XJYCS <>", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsGreaterThan(String value) {
			addCriterion("XJYCS >", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsGreaterThanOrEqualTo(String value) {
			addCriterion("XJYCS >=", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsLessThan(String value) {
			addCriterion("XJYCS <", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsLessThanOrEqualTo(String value) {
			addCriterion("XJYCS <=", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsLike(String value) {
			addCriterion("XJYCS like", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsNotLike(String value) {
			addCriterion("XJYCS not like", value, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsIn(List<String> values) {
			addCriterion("XJYCS in", values, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsNotIn(List<String> values) {
			addCriterion("XJYCS not in", values, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsBetween(String value1, String value2) {
			addCriterion("XJYCS between", value1, value2, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXjycsNotBetween(String value1, String value2) {
			addCriterion("XJYCS not between", value1, value2, "xjycs");
			return (Criteria) this;
		}

		public Criteria andXszrnlIsNull() {
			addCriterion("XSZRNL is null");
			return (Criteria) this;
		}

		public Criteria andXszrnlIsNotNull() {
			addCriterion("XSZRNL is not null");
			return (Criteria) this;
		}

		public Criteria andXszrnlEqualTo(String value) {
			addCriterion("XSZRNL =", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlNotEqualTo(String value) {
			addCriterion("XSZRNL <>", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlGreaterThan(String value) {
			addCriterion("XSZRNL >", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlGreaterThanOrEqualTo(String value) {
			addCriterion("XSZRNL >=", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlLessThan(String value) {
			addCriterion("XSZRNL <", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlLessThanOrEqualTo(String value) {
			addCriterion("XSZRNL <=", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlLike(String value) {
			addCriterion("XSZRNL like", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlNotLike(String value) {
			addCriterion("XSZRNL not like", value, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlIn(List<String> values) {
			addCriterion("XSZRNL in", values, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlNotIn(List<String> values) {
			addCriterion("XSZRNL not in", values, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlBetween(String value1, String value2) {
			addCriterion("XSZRNL between", value1, value2, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andXszrnlNotBetween(String value1, String value2) {
			addCriterion("XSZRNL not between", value1, value2, "xszrnl");
			return (Criteria) this;
		}

		public Criteria andSfctIsNull() {
			addCriterion("SFCT is null");
			return (Criteria) this;
		}

		public Criteria andSfctIsNotNull() {
			addCriterion("SFCT is not null");
			return (Criteria) this;
		}

		public Criteria andSfctEqualTo(String value) {
			addCriterion("SFCT =", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctNotEqualTo(String value) {
			addCriterion("SFCT <>", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctGreaterThan(String value) {
			addCriterion("SFCT >", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctGreaterThanOrEqualTo(String value) {
			addCriterion("SFCT >=", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctLessThan(String value) {
			addCriterion("SFCT <", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctLessThanOrEqualTo(String value) {
			addCriterion("SFCT <=", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctLike(String value) {
			addCriterion("SFCT like", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctNotLike(String value) {
			addCriterion("SFCT not like", value, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctIn(List<String> values) {
			addCriterion("SFCT in", values, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctNotIn(List<String> values) {
			addCriterion("SFCT not in", values, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctBetween(String value1, String value2) {
			addCriterion("SFCT between", value1, value2, "sfct");
			return (Criteria) this;
		}

		public Criteria andSfctNotBetween(String value1, String value2) {
			addCriterion("SFCT not between", value1, value2, "sfct");
			return (Criteria) this;
		}

		public Criteria andXwIsNull() {
			addCriterion("XW is null");
			return (Criteria) this;
		}

		public Criteria andXwIsNotNull() {
			addCriterion("XW is not null");
			return (Criteria) this;
		}

		public Criteria andXwEqualTo(String value) {
			addCriterion("XW =", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwNotEqualTo(String value) {
			addCriterion("XW <>", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwGreaterThan(String value) {
			addCriterion("XW >", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwGreaterThanOrEqualTo(String value) {
			addCriterion("XW >=", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwLessThan(String value) {
			addCriterion("XW <", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwLessThanOrEqualTo(String value) {
			addCriterion("XW <=", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwLike(String value) {
			addCriterion("XW like", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwNotLike(String value) {
			addCriterion("XW not like", value, "xw");
			return (Criteria) this;
		}

		public Criteria andXwIn(List<String> values) {
			addCriterion("XW in", values, "xw");
			return (Criteria) this;
		}

		public Criteria andXwNotIn(List<String> values) {
			addCriterion("XW not in", values, "xw");
			return (Criteria) this;
		}

		public Criteria andXwBetween(String value1, String value2) {
			addCriterion("XW between", value1, value2, "xw");
			return (Criteria) this;
		}

		public Criteria andXwNotBetween(String value1, String value2) {
			addCriterion("XW not between", value1, value2, "xw");
			return (Criteria) this;
		}

		public Criteria andZzmmIsNull() {
			addCriterion("ZZMM is null");
			return (Criteria) this;
		}

		public Criteria andZzmmIsNotNull() {
			addCriterion("ZZMM is not null");
			return (Criteria) this;
		}

		public Criteria andZzmmEqualTo(String value) {
			addCriterion("ZZMM =", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmNotEqualTo(String value) {
			addCriterion("ZZMM <>", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmGreaterThan(String value) {
			addCriterion("ZZMM >", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmGreaterThanOrEqualTo(String value) {
			addCriterion("ZZMM >=", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmLessThan(String value) {
			addCriterion("ZZMM <", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmLessThanOrEqualTo(String value) {
			addCriterion("ZZMM <=", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmLike(String value) {
			addCriterion("ZZMM like", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmNotLike(String value) {
			addCriterion("ZZMM not like", value, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmIn(List<String> values) {
			addCriterion("ZZMM in", values, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmNotIn(List<String> values) {
			addCriterion("ZZMM not in", values, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmBetween(String value1, String value2) {
			addCriterion("ZZMM between", value1, value2, "zzmm");
			return (Criteria) this;
		}

		public Criteria andZzmmNotBetween(String value1, String value2) {
			addCriterion("ZZMM not between", value1, value2, "zzmm");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_dsrb
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 13 12:58:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}