package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.Argue;
import main.java.generator.po.ArgueExample;
import org.apache.ibatis.annotations.Param;

public interface ArgueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    long countByExample(ArgueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByExample(ArgueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insert(Argue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insertSelective(Argue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<Argue> selectByExampleWithBLOBs(ArgueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<Argue> selectByExample(ArgueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    Argue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") Argue record, @Param("example") ArgueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Argue record, @Param("example") ArgueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExample(@Param("record") Argue record, @Param("example") ArgueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeySelective(Argue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Argue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table argue
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKey(Argue record);
}