package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.EvidencePo;
import main.java.generator.po.EvidencePoExample;
import org.apache.ibatis.annotations.Param;

public interface EvidencePoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	long countByExample(EvidencePoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int deleteByExample(EvidencePoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int insert(EvidencePo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int insertSelective(EvidencePo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	List<EvidencePo> selectByExampleWithBLOBs(EvidencePoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	List<EvidencePo> selectByExample(EvidencePoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	EvidencePo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int updateByExampleSelective(@Param("record") EvidencePo record, @Param("example") EvidencePoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") EvidencePo record, @Param("example") EvidencePoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int updateByExample(@Param("record") EvidencePo record, @Param("example") EvidencePoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int updateByPrimaryKeySelective(EvidencePo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(EvidencePo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evidence
	 * @mbg.generated  Thu Apr 20 16:55:49 CST 2017
	 */
	int updateByPrimaryKey(EvidencePo record);
}