package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.Evidence;
import main.java.generator.po.EvidenceExample;
import org.apache.ibatis.annotations.Param;

public interface EvidenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    long countByExample(EvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByExample(EvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insert(Evidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insertSelective(Evidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<Evidence> selectByExampleWithBLOBs(EvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<Evidence> selectByExample(EvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    Evidence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") Evidence record, @Param("example") EvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Evidence record, @Param("example") EvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExample(@Param("record") Evidence record, @Param("example") EvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeySelective(Evidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Evidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKey(Evidence record);
}