package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.EvSubmitter;
import main.java.generator.po.EvSubmitterExample;
import org.apache.ibatis.annotations.Param;

public interface EvSubmitterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    long countByExample(EvSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByExample(EvSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insert(EvSubmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insertSelective(EvSubmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<EvSubmitter> selectByExample(EvSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    EvSubmitter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") EvSubmitter record, @Param("example") EvSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExample(@Param("record") EvSubmitter record, @Param("example") EvSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeySelective(EvSubmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKey(EvSubmitter record);
}