package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.ExamSubmitter;
import main.java.generator.po.ExamSubmitterExample;
import org.apache.ibatis.annotations.Param;

public interface ExamSubmitterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    long countByExample(ExamSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByExample(ExamSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insert(ExamSubmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insertSelective(ExamSubmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<ExamSubmitter> selectByExample(ExamSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    ExamSubmitter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") ExamSubmitter record, @Param("example") ExamSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExample(@Param("record") ExamSubmitter record, @Param("example") ExamSubmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeySelective(ExamSubmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKey(ExamSubmitter record);
}