package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.ExamSubmmitter;
import main.java.generator.po.ExamSubmmitterExample;
import org.apache.ibatis.annotations.Param;

public interface ExamSubmmitterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    long countByExample(ExamSubmmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByExample(ExamSubmmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insert(ExamSubmmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insertSelective(ExamSubmmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<ExamSubmmitter> selectByExample(ExamSubmmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    ExamSubmmitter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") ExamSubmmitter record, @Param("example") ExamSubmmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExample(@Param("record") ExamSubmmitter record, @Param("example") ExamSubmmitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeySelective(ExamSubmmitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examsubmmitter
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKey(ExamSubmmitter record);
}