package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.Fact;
import main.java.generator.po.FactExample;
import org.apache.ibatis.annotations.Param;

public interface FactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    long countByExample(FactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByExample(FactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insert(Fact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int insertSelective(Fact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<Fact> selectByExampleWithBLOBs(FactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    List<Fact> selectByExample(FactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    Fact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") Fact record, @Param("example") FactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Fact record, @Param("example") FactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByExample(@Param("record") Fact record, @Param("example") FactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeySelective(Fact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Fact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fact
     *
     * @mbg.generated Thu Apr 27 15:03:15 CST 2017
     */
    int updateByPrimaryKey(Fact record);
}