package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.Law;
import main.java.generator.po.LawExample;
import org.apache.ibatis.annotations.Param;

public interface LawMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table law
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	long countByExample(LawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table law
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	int deleteByExample(LawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table law
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	int insert(Law record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table law
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	int insertSelective(Law record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table law
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	List<Law> selectByExample(LawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table law
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Law record, @Param("example") LawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table law
	 * @mbg.generated  Wed Apr 26 20:11:08 CST 2017
	 */
	int updateByExample(@Param("record") Law record, @Param("example") LawExample example);
}