package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.WsAjjbxxb;
import main.java.generator.po.WsAjjbxxbExample;
import org.apache.ibatis.annotations.Param;

public interface WsAjjbxxbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    long countByExample(WsAjjbxxbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int deleteByExample(WsAjjbxxbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int deleteByPrimaryKey(Integer ajxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int insert(WsAjjbxxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int insertSelective(WsAjjbxxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    List<WsAjjbxxb> selectByExample(WsAjjbxxbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    WsAjjbxxb selectByPrimaryKey(Integer ajxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") WsAjjbxxb record, @Param("example") WsAjjbxxbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int updateByExample(@Param("record") WsAjjbxxb record, @Param("example") WsAjjbxxbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int updateByPrimaryKeySelective(WsAjjbxxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_ajjbxxb
     *
     * @mbg.generated Thu Apr 20 16:55:49 CST 2017
     */
    int updateByPrimaryKey(WsAjjbxxb record);
}