package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.WsDsrQzcsPo;
import main.java.generator.po.WsDsrQzcsPoExample;
import org.apache.ibatis.annotations.Param;

public interface WsDsrQzcsPoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsr_qk
	 * @mbg.generated  Thu Apr 13 13:22:33 CST 2017
	 */
	long countByExample(WsDsrQzcsPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsr_qk
	 * @mbg.generated  Thu Apr 13 13:22:33 CST 2017
	 */
	int deleteByExample(WsDsrQzcsPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsr_qk
	 * @mbg.generated  Thu Apr 13 13:22:33 CST 2017
	 */
	int insert(WsDsrQzcsPo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsr_qk
	 * @mbg.generated  Thu Apr 13 13:22:33 CST 2017
	 */
	int insertSelective(WsDsrQzcsPo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsr_qk
	 * @mbg.generated  Thu Apr 13 13:22:33 CST 2017
	 */
	List<WsDsrQzcsPo> selectByExample(WsDsrQzcsPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsr_qk
	 * @mbg.generated  Thu Apr 13 13:22:33 CST 2017
	 */
	int updateByExampleSelective(@Param("record") WsDsrQzcsPo record, @Param("example") WsDsrQzcsPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsr_qk
	 * @mbg.generated  Thu Apr 13 13:22:33 CST 2017
	 */
	int updateByExample(@Param("record") WsDsrQzcsPo record, @Param("example") WsDsrQzcsPoExample example);
}