package main.java.generator.dao;

import java.util.List;
import main.java.generator.po.WsDsrbPo;
import main.java.generator.po.WsDsrbPoExample;
import org.apache.ibatis.annotations.Param;

public interface WsDsrbPoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	long countByExample(WsDsrbPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	int deleteByExample(WsDsrbPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	int insert(WsDsrbPo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	int insertSelective(WsDsrbPo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	List<WsDsrbPo> selectByExample(WsDsrbPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	int updateByExampleSelective(@Param("record") WsDsrbPo record, @Param("example") WsDsrbPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ws_dsrb
	 * @mbg.generated  Thu Apr 13 15:35:28 CST 2017
	 */
	int updateByExample(@Param("record") WsDsrbPo record, @Param("example") WsDsrbPoExample example);
}